### ISSUE TITLE
Compilation panic if code access unset values in structure

### ISSUE THREAD

**Issue by AlexVanin** [nspcc-dev/neo-go#1164]
neo-go version 0.90.0-pre-654-gf32920bf

Similar issue: #952

I have uninitialized values in the structure. If the code access them, compiler throws a panic.

```go
package foo
type Foo struct {
	y int
}
func NewFoo() Foo {
	return Foo{}
}
func Main() int {
	foo := NewFoo()
	return foo.y
}
```

I checked `int` values as in the examples and `slices`. Both throws panic.

```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 65 [running]:
testing.tRunner.func1.1(0xb33f80, 0xc000027fc0)
	/snap/go/current/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0002d3d40)
	/snap/go/current/src/testing/testing.go:943 +0x3f9
panic(0xb33f80, 0xc000027fc0)
	/snap/go/current/src/runtime/panic.go:969 +0x166
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).convertStruct(0xc0002a53f0, 0xc0002f8680)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/codegen.go:1318 +0x6bf
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).Visit(0xc0002a53f0, 0xc7b7a0, 0xc0002f8680, 0x0, 0x0)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/codegen.go:609 +0x14b6
go/ast.Walk(0xc763a0, 0xc0002a53f0, 0xc7b7a0, 0xc0002f8680)
	/snap/go/current/src/go/ast/walk.go:52 +0x66
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).Visit(0xc0002a53f0, 0xc7be60, 0xc0002f4fc0, 0x0, 0x0)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/codegen.go:494 +0x391d
go/ast.Walk(0xc763a0, 0xc0002a53f0, 0xc7be60, 0xc0002f4fc0)
	/snap/go/current/src/go/ast/walk.go:52 +0x66
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).Visit(0xc0002a53f0, 0xc7b5a0, 0xc0002fea50, 0x0, 0x0)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/codegen.go:899 +0x4821
go/ast.Walk(0xc763a0, 0xc0002a53f0, 0xc7b5a0, 0xc0002fea50)
	/snap/go/current/src/go/ast/walk.go:52 +0x66
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).convertFuncDecl(0xc0002a53f0, 0xc7b9a0, 0xc000157b00, 0xc0002fea80, 0xc0002fc640)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/codegen.go:338 +0x493
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).compile(0xc0002a53f0, 0xc0002f5260, 0xc0002a5340, 0xc0002a5340, 0x0)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/codegen.go:1464 +0x4ef
github.com/nspcc-dev/neo-go/pkg/compiler.CodeGen(0xc0002f5260, 0xc0002f4e80, 0xc0002f5260, 0x0, 0x0, 0xc0002fe801, 0xc0002f4e80)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/codegen.go:1494 +0x88
github.com/nspcc-dev/neo-go/pkg/compiler.CompileWithDebugInfo(0xc76c20, 0xc0002f4e80, 0xda4b58, 0xf, 0x0, 0x0, 0x0, 0x5151c0)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/compiler.go:80 +0x90
github.com/nspcc-dev/neo-go/pkg/compiler.Compile(...)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/compiler.go:66
github.com/nspcc-dev/neo-go/pkg/compiler_test.vmAndCompileInterop(0xc0002d3d40, 0xbac413, 0x94, 0x37e, 0x5151c0)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/vm_test.go:68 +0x110
github.com/nspcc-dev/neo-go/pkg/compiler_test.vmAndCompile(...)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/vm_test.go:58
github.com/nspcc-dev/neo-go/pkg/compiler_test.eval(0xc0002d3d40, 0xbac413, 0x94, 0xb7afa0, 0xc0001b2c00)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/vm_test.go:35 +0x49
github.com/nspcc-dev/neo-go/pkg/compiler_test.runTestCases.func1(0xc0002d3d40)
	/home/alexvanin/Project/Neo/neo-go/pkg/compiler/vm_test.go:24 +0x53
testing.tRunner(0xc0002d3d40, 0xc0002d8960)
	/snap/go/current/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/snap/go/current/src/testing/testing.go:1042 +0x357
```

**Comment by roman-khimov** [comment]
Shouldn't be hard to fix based on bf6aa02dcfc2d2819b9853900c6d089aa59a827c, but taking into account that there is a proper NULL in NeoVM 3 (that is to be used where `nil` is being used in Go).
