### ISSUE TITLE
Node fails in Testnet Preview3

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neo-go#1436]
I started a neo-go node to join testnet preview3 network of version `v0.91.0-support-1` and configuration below
```
ProtocolConfiguration:
  Magic: 1951352142
  SecondsPerBlock: 15
  MemPoolSize: 50000
  StandbyCommittee:
  - 023e9b32ea89b94d066e649b124fd50e396ee91369e8e2a6ae1b11c170d022256d
  - 03009b7540e10f2562e5fd8fac9eaec25166a58b26e412348ff5a86927bfac22a2
  - 02ba2c70f5996f357a43198705859fae2cfea13e1172962800772b3d588a9d4abd
  - 03408dcd416396f64783ac587ea1e1593c57d9fea880c8a6a1920e92a259477806
  - 02a7834be9b32e2981d157cb5bbd3acb42cfd11ea5c3b10224d7a44e98c5910f1b
  - 0214baf0ceea3a66f17e7e1e839ea25fd8bed6cd82e6bb6e68250189065f44ff01
  - 030205e9cefaea5a1dfc580af20c8d5aa2468bb0148f1a5e4605fc622c80e604ba
  ValidatorsCount: 7
  SeedList:
  - seed1t.neo.org:20333
  - seed2t.neo.org:20333
  - seed3t.neo.org:20333
  - seed4t.neo.org:20333
  - seed5t.neo.org:20333
  VerifyBlocks: true
  VerifyTransactions: false
ApplicationConfiguration:
  DBConfiguration:
    Type: "leveldb"
    LevelDBOptions:
      DataDirectoryPath: "/var/lib/neo-go/testnet"
  NodePort: 20333
  Relay: true
  DialTimeout: 3
  ProtoTickInterval: 2
  PingInterval: 30
  PingTimeout: 90
  MaxPeers: 100
  MinPeers: 5
  AttemptConnPeers: 20
  RPC:
    Enabled: true
    MaxGasInvoke: 10
    EnableCORSWorkaround: false
    Port: 20332
  Prometheus:
    Enabled: True
    Port: 2112
  Pprof:
    Enabled: False
    Port: 2113
  UnlockWallet:
    Path: "/etc/neo-go/wallet.json"
    Password: "<wallet_password>"
```
The node runs in docker container and managed by systemd.
When I start the node, it connects to some peers, but in about a minute fails with this trace:
```
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]: 2020-09-28T15:32:37.984-0400        INFO        received PrepareRequest        {"validator": 1, "tx": 0}
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]: panic: runtime error: index out of range [-1]
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]: goroutine 198 [running]:
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]: github.com/nspcc-dev/dbft.(*Context).makePrepareResponse(0xc0000dafc0, 0x102f9e0, 0xc00161c000)
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]:         github.com/nspcc-dev/dbft@v0.0.0-20200711144034-c526ccc6f570/send.go:98 +0x158
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]: github.com/nspcc-dev/dbft.(*DBFT).sendPrepareResponse(0xc0000dafc0)
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]:         github.com/nspcc-dev/dbft@v0.0.0-20200711144034-c526ccc6f570/send.go:104 +0x45
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]: github.com/nspcc-dev/dbft.(*DBFT).onPrepareRequest(0xc0000dafc0, 0x1033240, 0xc00265a6c0)
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]:         github.com/nspcc-dev/dbft@v0.0.0-20200711144034-c526ccc6f570/dbft.go:319 +0xe96
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]: github.com/nspcc-dev/dbft.(*DBFT).OnReceive(0xc0000dafc0, 0x1033240, 0xc00265a6c0)
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]:         github.com/nspcc-dev/dbft@v0.0.0-20200711144034-c526ccc6f570/dbft.go:233 +0xf65
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]: github.com/nspcc-dev/neo-go/pkg/consensus.(*service).eventLoop(0xc0000d2000)
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]:         github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:223 +0x797
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]: created by github.com/nspcc-dev/neo-go/pkg/consensus.(*service).Start
Sep 28 15:32:37 lobachevsky-1 neo-go[31539]:         github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:186 +0x9b
Sep 28 15:32:38 lobachevsky-1 systemd[1]: neo-go-testnet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
Did I misconfigured the node or it fails due to a bug?

**Comment by roman-khimov** [comment]
Looks very similar to #1314 (the problem is in the dbft library actually and it was fixed there), 9c5ef8d234fe8d44f5217b88f30c672c23606fd8 in the master branch should fix that.
