### ISSUE TITLE
CI/CD: Fix inconsistent build

### ISSUE THREAD

**Issue by decentralisedkev** [nspcc-dev/neo-go#212]
For some reason travis takes a while on one of the two builds and usually times out. When it is restarted it usually passes cleanly, but this happens quite often that I believe something is wrong with the build

**Comment by decentralisedkev** [comment]
More info using -v:

```
=== RUN   TestHandshake
SIGQUIT: quit
PC=0x488651 m=0 sigcode=0
goroutine 0 [idle]:
runtime.futex(0xb530c0, 0x80, 0x0, 0x0, 0x0, 0x7ffc0a523ca8, 0x0, 0x0, 0x7ffc0a523b60, 0x4337a2, ...)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0xb530c0, 0x0, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0xb530c0)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/lock_futex.go:151 +0xa2
runtime.stopm()
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/proc.go:2016 +0xe3
runtime.findrunnable(0xc000030000, 0x0)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/proc.go:2487 +0x4dc
runtime.schedule()
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/proc.go:2613 +0x13a
runtime.park_m(0xc000001980)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/proc.go:2676 +0xae
runtime.mcall(0x0)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/asm_amd64.s:299 +0x5b
goroutine 1 [chan receive]:
testing.(*T).Run(0xc000106000, 0x88bd89, 0xd, 0x89e7a8, 0xc0000c9bb0)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/testing/testing.go:879 +0x692
testing.runTests.func1(0xc000106000)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/testing/testing.go:1119 +0xa9
testing.tRunner(0xc000106000, 0xc0000c9d20)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/testing/testing.go:827 +0x163
testing.runTests(0xc00000c3c0, 0xb4c720, 0x4, 0x4, 0xc0000c9dc8)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/testing/testing.go:1117 +0x4ef
testing.(*M).Run(0xc000104000, 0x0)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/testing/testing.go:1034 +0x2ef
main.main()
	_testmain.go:104 +0x333
goroutine 5 [IO wait]:
internal/poll.runtime_pollWait(0x7fc0b9c4ef00, 0x72, 0xc000055b78)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000104098, 0x72, 0x0, 0x0, 0x8ee940)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0xe4
internal/poll.(*pollDesc).waitRead(0xc000104098, 0xffffffffffffff00, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x4b
internal/poll.(*FD).Accept(0xc000104080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/internal/poll/fd_unix.go:384 +0x27f
net.(*netFD).accept(0xc000104080, 0x3, 0x889ecc, 0x6)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/net/fd_unix.go:238 +0x53
net.(*TCPListener).accept(0xc00000e058, 0x3, 0x889ecc, 0x6)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).Accept(0xc00000e058, 0x89e7a0, 0x8f0960, 0xc00000e058, 0x8f0960)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/net/tcpsock.go:260 +0x50
github.com/CityOfZion/neo-go/pkg/peer_test.TestHandshake(0xc000106100)
	/home/travis/gopath/src/github.com/CityOfZion/neo-go/pkg/peer/peer_test.go:84 +0x1b0
testing.tRunner(0xc000106100, 0x89e7a8)
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.11.6.linux.amd64/src/testing/testing.go:878 +0x65a
rax    0xca
rbx    0xb52f80
rcx    0x488653
rdx    0x0
rdi    0xb530c0
rsi    0x80
rbp    0x7ffc0a523b28
rsp    0x7ffc0a523ae0
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc000055af0
r13    0xb52f80
r14    0xc000001980
r15    0xc000104098
rip    0x488651
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/CityOfZion/neo-go/pkg/peer	600.006s
```

**Comment by roman-khimov** [comment]
Closing as unreproducible with current master.
