### ISSUE TITLE
panic: inappropriate ioctl for device for stdin

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#2243]
In fact I'd expect password will used from stdin, but it must not panic.

```
% ./neo-go wallet init --account --wallet test.json
% echo qwe | ./neo-go wallet export --wallet test.json --decrypt NM74dkwaz8nG1jMJpAYeB5AwqAGGuymaSL
panic: inappropriate ioctl for device

goroutine 1 [running]:
github.com/nspcc-dev/neo-go/cli/input.ReadPassword({0x1004a92, 0x11})
	github.com/nspcc-dev/neo-go/cli/input/input.go:54 +0x277
github.com/nspcc-dev/neo-go/cli/wallet.exportKeys(0xc000456420)
	github.com/nspcc-dev/neo-go/cli/wallet/wallet.go:373 +0x571
github.com/urfave/cli.HandleAction({0xe6f6c0, 0x116c338}, 0x6)
	github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0xff9d3d, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x100c575, 0x17}, {0x10295e3, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00045a1c0, 0xc000456160)
	github.com/urfave/cli@v1.22.5/app.go:405 +0x9ec
github.com/urfave/cli.Command.startApp({{0xffa6df, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x101e2d0, 0x24}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:372 +0x6e9
github.com/urfave/cli.Command.Run({{0xffa6df, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x101e2d0, 0x24}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc00045a000, {0xc00011c000, 0x7, 0x7})
	github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.main()
	github.com/nspcc-dev/neo-go/cli/main.go:19 +0x33
zsh: done       echo qwe | 
zsh: exit 2     ./neo-go wallet export --wallet test.json --decrypt 
```

**Comment by roman-khimov** [comment]
> In fact I'd expect password will used from stdin

That's a wrong expectation, check ssh behavior for example.

But we might also return this error and shutdown in a bit more user-friendly manner.
