### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#2340]
```
% ../neo-go wallet nep17 transfer -r https://rpc01.testnet.n3.nspcc.ru:21331 -w secret.interweb/wallets/mona/cdn_billing-testnet/wallet.json --from NQgjuLbEzWYqzs1krT7YrDtSDdQU8JFdPS --to NadZ8YfvkddivcFFkztZgfwxZyKf1acpRF --token GAS --amount 10
Password > 
Network fee: 0.00123252
System fee: 0.01451339
Total fee: 0.01574591
Relay transaction (y|N)>              <--- just hit return here
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/nspcc-dev/neo-go/cli/input.ConfirmTx({0x11d2060, 0xc000138008}, 0xc000354a50)
	github.com/nspcc-dev/neo-go/cli/input/input.go:72 +0x19c
github.com/nspcc-dev/neo-go/cli/wallet.signAndSendNEP17Transfer(0xc0000cf600, 0xc0000ec090, 0x8, {0xc0014064a0, 0x1, 0x1}, {0x198ff70, 0x0, 0x0})
	github.com/nspcc-dev/neo-go/cli/wallet/nep17.go:590 +0x333
github.com/nspcc-dev/neo-go/cli/wallet.transferNEP(0xc0000cf600, {0xf55f92, 0x6})
	github.com/nspcc-dev/neo-go/cli/wallet/nep17.go:550 +0xf25
github.com/nspcc-dev/neo-go/cli/wallet.transferNEP17(0xc0000cf600)
	github.com/nspcc-dev/neo-go/cli/wallet/nep17.go:488 +0x25
github.com/urfave/cli.HandleAction({0xddb220, 0x10c54c0}, 0x8)
	github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0xf5936f, 0x8}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xf67b3b, 0x16}, {0xf9472f, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000372540, 0xc0000cf340)
	github.com/urfave/cli@v1.22.5/app.go:405 +0x9ec
github.com/urfave/cli.Command.startApp({{0xf55792, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xf6ccc9, 0x1a}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:372 +0x6e9
github.com/urfave/cli.Command.Run({{0xf55792, 0x5}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xf6ccc9, 0x1a}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000372380, 0xc0000cf1e0)
	github.com/urfave/cli@v1.22.5/app.go:405 +0x9ec
github.com/urfave/cli.Command.startApp({{0xf56f88, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xf7953c, 0x24}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:372 +0x6e9
github.com/urfave/cli.Command.Run({{0xf56f88, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xf7953c, 0x24}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc0003721c0, {0xc00013c000, 0x10, 0x10})
	github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.main()
	github.com/nspcc-dev/neo-go/cli/main.go:19 +0x33
zsh: exit 2     ../neo-go wallet nep17 transfer -r https://rpc01.testnet.n3.nspcc.ru:21331 -w
```

**Comment by roman-khimov** [comment]
Duplicates #2307.

**Comment by 532910** [comment]
Sorry \:
