### ISSUE TITLE
Panic on send to naive WS Client's receiver with filter

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2835]
```
panic: interface conversion: interface {} is *neorpc.BlockFilter, not neorpc.BlockFilter

goroutine 61 [running]:
[github.com/nspcc-dev/neo-go/pkg/neorpc/rpcevent.Matches({0x1304608,](http://github.com/nspcc-dev/neo-go/pkg/neorpc/rpcevent.Matches(%7B0x1304608,) 0xc0002e0120}, {0x13089b0, 0xc0002d3f38})
        /home/kira/work/neofs-cdn-edge-manager/vendor/[github.com/nspcc-dev/neo-go/pkg/neorpc/rpcevent/filter.go:38](http://github.com/nspcc-dev/neo-go/pkg/neorpc/rpcevent/filter.go:38) +0xd05
[github.com/nspcc-dev/neo-go/pkg/rpcclient.(*naiveReceiver).TrySend(0xc0002e0120,](http://github.com/nspcc-dev/neo-go/pkg/rpcclient.(*naiveReceiver).TrySend(0xc0002e0120,) {0x1, {0x1151de0, 0xc0002e2d80}})
        /home/kira/work/neofs-cdn-edge-manager/vendor/[github.com/nspcc-dev/neo-go/pkg/rpcclient/wsclient.go:296](http://github.com/nspcc-dev/neo-go/pkg/rpcclient/wsclient.go:296) +0x8e
[github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).wsReader(0xc00025b680)](http://github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).wsReader(0xc00025b680))
        /home/kira/work/neofs-cdn-edge-manager/vendor/[github.com/nspcc-dev/neo-go/pkg/rpcclient/wsclient.go:494](http://github.com/nspcc-dev/neo-go/pkg/rpcclient/wsclient.go:494) +0x1462
created by [github.com/nspcc-dev/neo-go/pkg/rpcclient.NewWS](http://github.com/nspcc-dev/neo-go/pkg/rpcclient.NewWS)
        /home/kira/work/neofs-cdn-edge-manager/vendor/[github.com/nspcc-dev/neo-go/pkg/rpcclient/wsclient.go:390](http://github.com/nspcc-dev/neo-go/pkg/rpcclient/wsclient.go:390) +0x7c5
```
Thanks to @masterSplinter01 for discovering. Could you please, specify the NeoGo version for clarification?

**Comment by masterSplinter01** [comment]
v0.99.7
