### ISSUE TITLE
divide by zero panic when trying to restore from offline chain

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#2849]
I'm trying to restore a db from an offline chain I downloaded here: https://sync.ngd.network/
Using the N3Mainnet file I do the following
```bash
erik@erik-linux:~/Documents/code/neo-go$ md5sum ~/Downloads/chain.0.acc.zip 
8d706ece6375201046958616381c677e  /home/erik/Downloads/chain.0.acc.zip
erik@erik-linux:~/Documents/code/neo-go$ unzip ~/Downloads/chain.0.acc.zip
Archive:  /home/erik/Downloads/chain.0.acc.zip
  inflating: chain.0.acc             
erik@erik-linux:~/Documents/code/neo-go$ ./bin/neo-go db restore -i chain.0.acc -m
2022-12-21T11:06:44.653+0100	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2022-12-21T11:06:44.653+0100	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2022-12-21T11:06:44.653+0100	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/nspcc-dev/neo-go/pkg/core.NewBlockchain({0x1263b70?, 0xc000116030}, {0x0, 0x0, 0x334f454e, 0xc350, 0xc00011bbc0, 0x12795f58d50000, 0x0, 0x0, ...}, ...)
	github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:251 +0x1718
github.com/nspcc-dev/neo-go/cli/server.initBlockChain({{0x0, 0x0, 0x334f454e, 0xc350, 0xc00011bbc0, 0x12795f58d50000, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/cli/server/server.go:678 +0x165
github.com/nspcc-dev/neo-go/cli/server.initBCWithMetrics({{0x0, 0x0, 0x334f454e, 0xc350, 0xc00011bbc0, 0x12795f58d50000, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/cli/server/server.go:217 +0x58
github.com/nspcc-dev/neo-go/cli/server.restoreDB(0xc000172420)
	github.com/nspcc-dev/neo-go/cli/server/server.go:317 +0x465
github.com/urfave/cli.HandleAction({0xe243c0?, 0x1131460?}, 0x7?)
	github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0xfa9f4b, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xfc2828, 0x1c}, {0xfe7d1d, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).RunAsSubcommand(0xc0001741c0, 0xc000172160)
	github.com/urfave/cli@v1.22.5/app.go:405 +0x91b
github.com/urfave/cli.Command.startApp({{0xfa5cce, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xfb97f5, 0x16}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:372 +0x6e7
github.com/urfave/cli.Command.Run({{0xfa5cce, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xfb97f5, 0x16}, {0x0, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc000174000, {0xc00003a1e0, 0x6, 0x6})
	github.com/urfave/cli@v1.22.5/app.go:277 +0x8a7
main.main()
	./main.go:21 +0x33
```
running latest commit as of writing
```
erik@erik-linux:~/Documents/code/neo-go$ git log -n1
commit 5fb9e1353de2e495ed2d314fab0c6f38ab55f0a2 (HEAD -> master, origin/master, origin/HEAD)
Merge: 3e714a34 3339824f
Author: Roman Khimov <roman@nspcc.ru>
Date:   Mon Dec 19 13:41:07 2022 +0700

    Merge pull request #2848 from nspcc-dev/tune-management-callflags-for-aspidochelone
    
    Tune management callflags for aspidochelone
```

The same file syncs fine with `neo-cli 3.5.0`.

**Comment by ixje** [comment]
Not sure what I'm doing wrong. Considering I see no `make clean` I just did another `make` after pulling latest changes this is what I get
```
./bin/neo-go --version
NeoGo
Version: 0.100.1-pre-7-g5fb9e135
GoVersion: go1.18.1
```
then after some google I tried
```
go clean --cache && make
```
same output

**Comment by ixje** [comment]
regular sync has no issues
```
erik@erik-linux:~/Documents/code/neo-go$ ./bin/neo-go node -m
2022-12-21T19:23:06.192+0100	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2022-12-21T19:23:06.194+0100	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2022-12-21T19:23:06.194+0100	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2022-12-21T19:23:06.194+0100	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2022-12-21T19:23:06.195+0100	INFO	no storage version found! creating genesis block
2022-12-21T19:23:06.197+0100	INFO	starting service	{"service": "Prometheus", "endpoint": ":2112"}
2022-12-21T19:23:06.199+0100	INFO	service hasn't started since it's disabled	{"service": "Pprof"}
2022-12-21T19:23:06.199+0100	INFO	ExtensiblePoolSize is not set or wrong, using default value	{"ExtensiblePoolSize": 20}
2022-12-21T19:23:06.199+0100	INFO	MaxWebSocketClients is not set or wrong, setting default value	{"MaxWebSocketClients": 64}
2022-12-21T19:23:06.199+0100	INFO	starting rpc-server	{"endpoint": ":10332"}

    _   ____________        __________
   / | / / ____/ __ \      / ____/ __ \
  /  |/ / __/ / / / /_____/ / __/ / / /
 / /|  / /___/ /_/ /_____/ /_/ / /_/ /
/_/ |_/_____/\____/      \____/\____/

/NEO-GO:0.100.1-pre-7-g5fb9e135/

2022-12-21T19:23:06.199+0100	INFO	node started	{"blockHeight": 0, "headerHeight": 0}
2022-12-21T19:23:06.567+0100	INFO	new peer connected	{"addr": "20.198.226.132:10333", "peerCount": 1}
2022-12-21T19:23:06.627+0100	INFO	new peer connected	{"addr": "20.55.44.83:10333", "peerCount": 2}
2022-12-21T19:23:06.713+0100	INFO	new peer connected	{"addr": "20.55.43.229:10333", "peerCount": 3}
2022-12-21T19:23:06.719+0100	INFO	started protocol	{"addr": "20.55.44.83:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 2094913991}
2022-12-21T19:23:06.739+0100	INFO	started protocol	{"addr": "20.198.226.132:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 121463374}
2022-12-21T19:23:06.807+0100	INFO	new peer connected	{"addr": "20.84.53.54:10333", "peerCount": 4}
2022-12-21T19:23:06.812+0100	INFO	started protocol	{"addr": "20.55.43.229:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 284647194}
2022-12-21T19:23:06.874+0100	INFO	new peer connected	{"addr": "20.198.226.113:10333", "peerCount": 5}
2022-12-21T19:23:06.905+0100	INFO	started protocol	{"addr": "20.84.53.54:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 1941206069}
2022-12-21T19:23:07.043+0100	INFO	started protocol	{"addr": "20.198.226.113:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 1065173500}
2022-12-21T19:23:07.200+0100	INFO	persisted to disk	{"blocks": 1, "keys": 110, "headerHeight": 1, "blockHeight": 1, "took": "2.785099ms"}
2022-12-21T19:23:08.204+0100	INFO	persisted to disk	{"blocks": 186, "keys": 2289, "headerHeight": 187, "blockHeight": 187, "took": "6.451049ms"}
2022-12-21T19:23:08.389+0100	INFO	new peer connected	{"addr": "65.21.105.228:10333", "peerCount": 6}
2022-12-21T19:23:08.432+0100	INFO	started protocol	{"addr": "65.21.105.228:10333", "userAgent": "/NEO-GO:0.99.6/", "startHeight": 2682357, "id": 3537259377}
2022-12-21T19:23:08.483+0100	INFO	new peer connected	{"addr": "157.90.177.38:10333", "peerCount": 7}
2022-12-21T19:23:08.513+0100	INFO	started protocol	{"addr": "157.90.177.38:10333", "userAgent": "/NEO-GO:0.99.6/", "startHeight": 2682357, "id": 2430140069}
2022-12-21T19:23:08.564+0100	INFO	new peer connected	{"addr": "20.184.10.14:10333", "peerCount": 8}
2022-12-21T19:23:08.593+0100	INFO	new peer connected	{"addr": "20.84.50.92:10333", "peerCount": 9}
2022-12-21T19:23:08.637+0100	INFO	new peer connected	{"addr": "129.213.36.133:10333", "peerCount": 10}
2022-12-21T19:23:08.638+0100	INFO	new peer connected	{"addr": "40.87.98.75:10333", "peerCount": 11}
2022-12-21T19:23:08.655+0100	INFO	new peer connected	{"addr": "65.108.97.115:10333", "peerCount": 12}
2022-12-21T19:23:08.664+0100	INFO	new peer connected	{"addr": "185.185.68.193:10333", "peerCount": 13}
2022-12-21T19:23:08.681+0100	INFO	new peer connected	{"addr": "13.68.253.120:10333", "peerCount": 14}
2022-12-21T19:23:08.698+0100	INFO	started protocol	{"addr": "20.84.50.92:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 1438274188}
2022-12-21T19:23:08.702+0100	WARN	peer disconnected	{"addr": "65.108.97.115:10333", "error": "unexpected empty payload: CMDVersion", "peerCount": 13}
2022-12-21T19:23:08.714+0100	INFO	started protocol	{"addr": "185.185.68.193:10333", "userAgent": "/NEO-GO:0.100.0/", "startHeight": 2682357, "id": 2749151093}
2022-12-21T19:23:08.716+0100	INFO	new peer connected	{"addr": "135.181.150.189:10333", "peerCount": 14}
2022-12-21T19:23:08.734+0100	INFO	started protocol	{"addr": "20.184.10.14:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 1469181141}
2022-12-21T19:23:08.745+0100	INFO	started protocol	{"addr": "129.213.36.133:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 753268090}
2022-12-21T19:23:08.745+0100	INFO	started protocol	{"addr": "40.87.98.75:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 1885571450}
2022-12-21T19:23:08.760+0100	INFO	started protocol	{"addr": "135.181.150.189:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 1474109880}
2022-12-21T19:23:08.772+0100	INFO	new peer connected	{"addr": "157.90.177.39:10333", "peerCount": 15}
2022-12-21T19:23:08.777+0100	INFO	started protocol	{"addr": "13.68.253.120:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 1028684768}
2022-12-21T19:23:08.801+0100	INFO	started protocol	{"addr": "157.90.177.39:10333", "userAgent": "/NEO-GO:0.99.6/", "startHeight": 2682357, "id": 2179338639}
2022-12-21T19:23:09.022+0100	INFO	new peer connected	{"addr": "39.103.188.6:10333", "peerCount": 16}
2022-12-21T19:23:09.255+0100	INFO	persisted to disk	{"blocks": 1897, "keys": 22684, "headerHeight": 2085, "blockHeight": 2084, "took": "58.098731ms"}
2022-12-21T19:23:09.754+0100	INFO	started protocol	{"addr": "39.103.188.6:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682357, "id": 595553340}
2022-12-21T19:23:10.222+0100	INFO	persisted to disk	{"blocks": 1130, "keys": 13596, "headerHeight": 3214, "blockHeight": 3214, "took": "24.014176ms"}
2022-12-21T19:23:11.230+0100	INFO	persisted to disk	{"blocks": 1143, "keys": 14221, "headerHeight": 4357, "blockHeight": 4357, "took": "31.463865ms"}
2022-12-21T19:23:12.076+0100	WARN	contract invocation failed	{"tx": "3d82c9a5da51d2163895c67672380e5a4ba26cba1d400098d75ae82475e6a712", "block": 5782, "error": "at instruction 0 (PUSH1): gas limit is exceeded"}
2022-12-21T19:23:12.241+0100	INFO	persisted to disk	{"blocks": 1721, "keys": 25002, "headerHeight": 6078, "blockHeight": 6078, "took": "42.440033ms"}
2022-12-21T19:23:13.243+0100	INFO	persisted to disk	{"blocks": 481, "keys": 6948, "headerHeight": 6559, "blockHeight": 6559, "took": "44.712363ms"}
2022-12-21T19:23:14.233+0100	INFO	persisted to disk	{"blocks": 1030, "keys": 14716, "headerHeight": 7589, "blockHeight": 7589, "took": "34.135444ms"}
2022-12-21T19:23:14.754+0100	INFO	new peer connected	{"addr": "47.100.41.188:10333", "peerCount": 17}
2022-12-21T19:23:14.973+0100	INFO	started protocol	{"addr": "47.100.41.188:10333", "userAgent": "/Neo:3.4.0/", "startHeight": 2682358, "id": 1060257578}
2022-12-21T19:23:15.251+0100	INFO	persisted to disk	{"blocks": 1812, "keys": 25976, "headerHeight": 9401, "blockHeight": 9401, "took": "52.331102ms"}
2022-12-21T19:23:15.896+0100	INFO	runtime log	{"tx": "823296b857a03c8019853150262031de18ee2724f4a295951c1502fcc65e70f1", "script": "2cafa46838e8b564468ebd868dcafdd99dce6221", "msg": "neofs contract notary disabled"}
2022-12-21T19:23:15.896+0100	INFO	runtime log	{"tx": "823296b857a03c8019853150262031de18ee2724f4a295951c1502fcc65e70f1", "script": "2cafa46838e8b564468ebd868dcafdd99dce6221", "msg": "neofs: contract initialized"}
2022-12-21T19:23:16.249+0100	INFO	persisted to disk	{"blocks": 1811, "keys": 26263, "headerHeight": 11212, "blockHeight": 11212, "took": "50.601342ms"}
2022-12-21T19:23:17.216+0100	INFO	persisted to disk	{"blocks": 511, "keys": 7422, "headerHeight": 11724, "blockHeight": 11723, "took": "16.988347ms"}
2022-12-21T19:23:18.255+0100	INFO	persisted to disk	{"blocks": 1730, "keys": 24891, "headerHeight": 13453, "blockHeight": 13453, "took": "56.061481ms"}
2022-12-21T19:23:19.215+0100	INFO	persisted to disk	{"blocks": 472, "keys": 6853, "headerHeight": 13925, "blockHeight": 13925, "took": "15.397457ms"}
2022-12-21T19:23:20.246+0100	INFO	persisted to disk	{"blocks": 1663, "keys": 24018, "headerHeight": 15588, "blockHeight": 15588, "took": "46.998143ms"}
2022-12-21T19:23:21.220+0100	INFO	persisted to disk	{"blocks": 1117, "keys": 16187, "headerHeight": 16705, "blockHeight": 16705, "took": "20.858147ms"}
2022-12-21T19:23:22.093+0100	WARN	contract invocation failed	{"tx": "f69aec87c76c6ce9fbec78cf201fd278aff5efff307b44b90f066fe3b99b5a9c", "block": 17177, "error": "at instruction 90 (ASSERT): ASSERT failed"}
2022-12-21T19:23:22.182+0100	INFO	runtime log	{"tx": "d7d2bbe1e66089586148561ea41e86e62602d35e42f46b7e5a7789a8c118cd09", "script": "2cafa46838e8b564468ebd868dcafdd99dce6221", "msg": "onNEP17Payment: funds have been transferred"}
2022-12-21T19:23:22.227+0100	INFO	persisted to disk	{"blocks": 660, "keys": 9561, "headerHeight": 17366, "blockHeight": 17365, "took": "27.717046ms"}
2022-12-21T19:23:22.237+0100	INFO	runtime log	{"tx": "cd52b2a05e26677b5171e0a9f5eb581619fbc54672453c1c1a63eadd13abe011", "script": "2cafa46838e8b564468ebd868dcafdd99dce6221", "msg": "onNEP17Payment: funds have been transferred"}
2022-12-21T19:23:22.239+0100	INFO	runtime log	{"tx": "864ae2da265d3bd88c69aa4e14236ecef267e37ebb7286944dd248d52e991334", "script": "2cafa46838e8b564468ebd868dcafdd99dce6221", "msg": "onNEP17Payment: funds have been transferred"}
2022-12-21T19:23:22.239+0100	INFO	runtime log	{"tx": "229d9d61fb5a22c4457fe9b07f3a03a07d7317e4f9a86fa4032dcd4ccf1420da", "script": "2cafa46838e8b564468ebd868dcafdd99dce6221", "msg": "onNEP17Payment: funds have been transferred"}
2022-12-21T19:23:22.318+0100	INFO	runtime log	{"tx": "97339f57c6820447b2204deec2aeebec5c4b21a0dc763ae19e6d0e8e4515ab1f", "script": "2cafa46838e8b564468ebd868dcafdd99dce6221", "msg": "onNEP17Payment: funds have been transferred"}
2022-12-21T19:23:23.247+0100	INFO	persisted to disk	{"blocks": 1600, "keys": 23228, "headerHeight": 18965, "blockHeight": 18965, "took": "47.359472ms"}
2022-12-21T19:23:25.216+0100	INFO	persisted to disk	{"blocks": 564, "keys": 8151, "headerHeight": 19530, "blockHeight": 19529, "took": "15.186737ms"}
2022-12-21T19:23:26.248+0100	INFO	persisted to disk	{"blocks": 1436, "keys": 22404, "headerHeight": 20965, "blockHeight": 20965, "took": "46.188412ms"}
2022-12-21T19:23:26.944+0100	WARN	contract invocation failed	{"tx": "aad56c80fd565f38ee4b7668cda3aae20c1880de5137906567db68a68eb0e466", "block": 21171, "error": "at instruction 90 (ASSERT): ASSERT failed"}
2022-12-21T19:23:27.221+0100	INFO	persisted to disk	{"blocks": 501, "keys": 8723, "headerHeight": 21466, "blockHeight": 21466, "took": "18.952387ms"}
2022-12-21T19:23:29.224+0100	INFO	persisted to disk	{"blocks": 556, "keys": 9534, "headerHeight": 22022, "blockHeight": 22022, "took": "21.172627ms"}
2022-12-21T19:23:30.252+0100	INFO	persisted to disk	{"blocks": 1445, "keys": 24795, "headerHeight": 23467, "blockHeight": 23467, "took": "48.389383ms"}
2022-12-21T19:23:31.219+0100	INFO	persisted to disk	{"blocks": 489, "keys": 8408, "headerHeight": 23956, "blockHeight": 23956, "took": "15.366053ms"}
2022-12-21T19:23:32.245+0100	INFO	persisted to disk	{"blocks": 1511, "keys": 25912, "headerHeight": 25467, "blockHeight": 25467, "took": "41.853781ms"}
^C2022-12-21T19:23:33.207+0100	INFO	shutting down server	{"peers": 17}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "20.198.226.132:10333", "error": "server shutdown", "peerCount": 16}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "20.55.43.229:10333", "error": "server shutdown", "peerCount": 15}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "20.84.50.92:10333", "error": "server shutdown", "peerCount": 14}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "20.84.53.54:10333", "error": "server shutdown", "peerCount": 13}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "20.184.10.14:10333", "error": "server shutdown", "peerCount": 12}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "47.100.41.188:10333", "error": "server shutdown", "peerCount": 11}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "129.213.36.133:10333", "error": "server shutdown", "peerCount": 10}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "40.87.98.75:10333", "error": "server shutdown", "peerCount": 9}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "185.185.68.193:10333", "error": "server shutdown", "peerCount": 8}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "13.68.253.120:10333", "error": "server shutdown", "peerCount": 7}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "157.90.177.39:10333", "error": "server shutdown", "peerCount": 6}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "20.55.44.83:10333", "error": "server shutdown", "peerCount": 5}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "20.198.226.113:10333", "error": "server shutdown", "peerCount": 4}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "65.21.105.228:10333", "error": "server shutdown", "peerCount": 3}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "157.90.177.38:10333", "error": "server shutdown", "peerCount": 2}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "135.181.150.189:10333", "error": "server shutdown", "peerCount": 1}
2022-12-21T19:23:33.207+0100	INFO	shutting down RPC server	{"endpoint": "[::]:10332"}
2022-12-21T19:23:33.207+0100	WARN	peer disconnected	{"addr": "39.103.188.6:10333", "error": "server shutdown", "peerCount": 0}
2022-12-21T19:23:33.213+0100	INFO	shutting down service	{"service": "Prometheus", "endpoint": "[::]:2112"}
2022-12-21T19:23:33.231+0100	INFO	persisted to disk	{"blocks": 672, "keys": 11628, "headerHeight": 26139, "blockHeight": 26139, "took": "27.407542ms"}
2022-12-21T19:23:33.238+0100	INFO	persisted to disk	{"blocks": 7, "keys": 208, "headerHeight": 26146, "blockHeight": 26146, "took": "7.093036ms"}
```

**Comment by roman-khimov** [comment]
For some reason I can't download `chain.0.acc` at the moment (404), but it looks like it's made as an incremental backup and not a full one (there is a difference in format between these two unfortunately), therefore you get this behaviour with zero blocks imported (please try `--incremental` option). At the same time I still can't explain the division by zero, my chain dumps (yes, I almost never use sync.ngd.network) work fine with the default config.

**Comment by roman-khimov** [comment]
IIRC regular dumps were always named as `chain.acc`, so `chain.0.acc` really look like an incremental one.

**Comment by ixje** [comment]
I'll try again tomorrow when I get the chance. I believe the `0` in the name is just the starting index. The `404` is probably because they auto updated it, as when I look now the hash has changed
https://packet.azureedge.net/neochain/n3mainnet/full/0-2681450/D1BCE6645DC417681E407C90C57C6D1F/chain.0.acc.zip

**Comment by roman-khimov** [comment]
> I believe the 0 in the name is just the starting index

It's not that easy, it's https://github.com/neo-project/neo-node/blob/master/neo-cli/CLI/MainService.cs#L173 vs https://github.com/neo-project/neo-node/blob/master/neo-cli/CLI/MainService.cs#L187 and then `read_start` at https://github.com/neo-project/neo-node/blob/master/neo-cli/CLI/MainService.cs#L148. Previously full chain dumps were always just `chain.acc`, `chain.X.acc` were always incremental ones.

**Comment by roman-khimov** [comment]
> https://packet.azureedge.net/neochain/n3mainnet/full/0-2681450/D1BCE6645DC417681E407C90C57C6D1F/chain.0.acc.zip

Yep, this one is incremental.

**Comment by ixje** [comment]
It works fine with `--incremental` so I'll consider this resolved for my case. Still don't understand the panic but that's not relevant for me at least.
