### ISSUE TITLE
Failing actor test

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2932]
```
2023-03-13T22:39:21.9408422Z panic: close of closed channel
2023-03-13T22:39:21.9408434Z 
2023-03-13T22:39:21.9408551Z goroutine 6780 [running]:
2023-03-13T22:39:21.9409042Z github.com/nspcc-dev/neo-go/pkg/rpcclient/actor.(*EventWaiter).WaitAny(0xc00bcf8120, {0x16c9ff8, 0xc000050118}, 0x1, {0xc00bcee140?, 0x1, 0x1})
2023-03-13T22:39:21.9409394Z 	/home/runner/work/neo-go/neo-go/pkg/rpcclient/actor/waiter.go:338 +0xb76
2023-03-13T22:39:21.9409857Z github.com/nspcc-dev/neo-go/pkg/rpcclient/actor.(*EventWaiter).Wait(0x4a4537?, {0x16, 0xb3, 0xaf, 0xc6, 0x0, 0x29, 0x8, 0xa1, 0x59, ...}, ...)
2023-03-13T22:39:21.9410203Z 	/home/runner/work/neo-go/neo-go/pkg/rpcclient/actor/waiter.go:226 +0xd3
2023-03-13T22:39:21.9410608Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.testSubClientWaitWithMissedEvent.func1()
2023-03-13T22:39:21.9410968Z 	/home/runner/work/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:2244 +0x15c
2023-03-13T22:39:21.9411349Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.testSubClientWaitWithMissedEvent
2023-03-13T22:39:21.9411710Z 	/home/runner/work/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:2243 +0x586
2023-03-13T22:39:21.9411993Z FAIL	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv	41.504s
```

**Comment by roman-khimov** [comment]
A channel should be closed by its creator. A channel can be closed by wsclient. Easy as that. Or not?
