### ISSUE TITLE
`TestRPC` timeout on Windows

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2975]
Either there's a Windows-specific bug or Windows tests just take too much time to pass and we need to extend testing time for Windows. Go 1.20.
[log.txt](https://github.com/nspcc-dev/neo-go/files/11240308/log.txt)

**Comment by ixje** [comment]
Has there perhaps been any undocumented investigation done related to this? We've wrapped `neo-go` for testing and a simple `invoke_script` RPC call takes ~2 seconds on Windows where it takes ~1ms on Linux.

**Comment by roman-khimov** [comment]
Not really. It's surprising, because we have so few platform-specific code (password reading and signal handling) and don't use CGO. It also looks like this is not related to the DB type/configuration (tests are all in-memory).

**Comment by ixje** [comment]
I've solved the problem on our side and I thought the solution might be worth sharing. 

If IPv6 is enabled in the network settings of the Windows machine then our `async rpc` library would first attempt to use IPv6 for the RPC calls. It takes a timeout before it falls back to IPv4 and this can be _long_. Disabling IPv6 in the TCP connector of our library solved the issue and now speeds are similar to Linux. Perhaps this is also happening in your case.

**Comment by roman-khimov** [comment]
```
2024-03-13T09:32:50.9095257Z panic: test timed out after 15m0s
2024-03-13T09:32:50.9095344Z running tests:
2024-03-13T09:32:50.9095521Z 	TestFilteredNotaryRequestSubscriptions (4m39s)
2024-03-13T09:32:50.9095775Z 	TestFilteredNotaryRequestSubscriptions/matching_signer (4m38s)
2024-03-13T09:32:50.9095784Z 
2024-03-13T09:32:50.9095879Z goroutine 11419 [running]:
2024-03-13T09:32:50.9095980Z testing.(*M).startAlarm.func1()
2024-03-13T09:32:50.9096272Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:2366 +0x265
2024-03-13T09:32:50.9096363Z created by time.goFunc
2024-03-13T09:32:50.9096606Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/time/sleep.go:177 +0x45
2024-03-13T09:32:50.9096612Z 
2024-03-13T09:32:50.9096730Z goroutine 1 [chan receive, 4 minutes]:
2024-03-13T09:32:50.9096922Z testing.(*T).Run(0xc00031a340, {0x141572eb8, 0x26}, 0x141678420)
2024-03-13T09:32:50.9097244Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1750 +0x851
2024-03-13T09:32:50.9097356Z testing.runTests.func1(0xc00031a340)
2024-03-13T09:32:50.9097628Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:2161 +0x86
2024-03-13T09:32:50.9097754Z testing.tRunner(0xc00031a340, 0xc000253b10)
2024-03-13T09:32:50.9098029Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1689 +0x21f
2024-03-13T09:32:50.9098371Z testing.runTests(0xc000302828, {0x1412c7440, 0x31, 0x31}, {0xc000253bb8?, 0xc000253c00?, 0x14210f0c0?})
2024-03-13T09:32:50.9098651Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:2159 +0x8bf
2024-03-13T09:32:50.9098746Z testing.(*M).Run(0xc00033e000)
2024-03-13T09:32:50.9099011Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:2027 +0xf18
2024-03-13T09:32:50.9099094Z main.main()
2024-03-13T09:32:50.9099196Z 	_testmain.go:145 +0x2be
2024-03-13T09:32:50.9099201Z 
2024-03-13T09:32:50.9099295Z goroutine 11789 [select]:
2024-03-13T09:32:50.9099601Z github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).Run(0xc001a06608)
2024-03-13T09:32:50.9099833Z 	D:/a/neo-go/neo-go/pkg/core/blockchain.go:1074 +0x2dc
2024-03-13T09:32:50.9100391Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.getUnitTestChainWithCustomConfig in goroutine 11787
2024-03-13T09:32:50.9101345Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/server_helper_test.go:85 +0x737
2024-03-13T09:32:50.9101353Z 
2024-03-13T09:32:50.9101466Z goroutine 11814 [select, 4 minutes]:
2024-03-13T09:32:50.9101830Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).broadcastTxLoop(0xc001923c08)
2024-03-13T09:32:50.9102057Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1689 +0x33b
2024-03-13T09:32:50.9102429Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9102643Z 	D:/a/neo-go/neo-go/pkg/network/server.go:293 +0x42b
2024-03-13T09:32:50.9102649Z 
2024-03-13T09:32:50.9102753Z goroutine 11819 [select, 4 minutes]:
2024-03-13T09:32:50.9103039Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).run(0xc001923c08)
2024-03-13T09:32:50.9103247Z 	D:/a/neo-go/neo-go/pkg/network/server.go:484 +0x919
2024-03-13T09:32:50.9103603Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9103815Z 	D:/a/neo-go/neo-go/pkg/network/server.go:303 +0x874
2024-03-13T09:32:50.9103823Z 
2024-03-13T09:32:50.9103926Z goroutine 11665 [select, 4 minutes]:
2024-03-13T09:32:50.9104289Z github.com/nspcc-dev/neo-go/pkg/core/mempool.(*Pool).notificationDispatcher(...)
2024-03-13T09:32:50.9104530Z 	D:/a/neo-go/neo-go/pkg/core/mempool/subscriptions.go:55
2024-03-13T09:32:50.9104983Z created by github.com/nspcc-dev/neo-go/pkg/core/mempool.(*Pool).RunSubscriptions in goroutine 11787
2024-03-13T09:32:50.9105254Z 	D:/a/neo-go/neo-go/pkg/core/mempool/subscriptions.go:13 +0xe5
2024-03-13T09:32:50.9105260Z 
2024-03-13T09:32:50.9105367Z goroutine 11792 [IO wait, 4 minutes]:
2024-03-13T09:32:50.9105552Z internal/poll.runtime_pollWait(0x48b102f0, 0x72)
2024-03-13T09:32:50.9105834Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/netpoll.go:345 +0x85
2024-03-13T09:32:50.9106001Z internal/poll.(*pollDesc).wait(0xc000235ac0, 0x72, 0x0)
2024-03-13T09:32:50.9106344Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-13T09:32:50.9106488Z internal/poll.execIO(0xc000235920, 0xc000af59f8)
2024-03-13T09:32:50.9106803Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:175 +0x271
2024-03-13T09:32:50.9107109Z internal/poll.(*FD).acceptOne(0xc000235908, 0x20c, {0xc0002f5d10, 0x2, 0x2}, 0xc000235920)
2024-03-13T09:32:50.9107423Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:944 +0xf8
2024-03-13T09:32:50.9107582Z internal/poll.(*FD).Accept(0xc000235908, 0xc000b2fc70)
2024-03-13T09:32:50.9107903Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:978 +0x3cb
2024-03-13T09:32:50.9108040Z net.(*netFD).accept(0xc000235908)
2024-03-13T09:32:50.9108301Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/fd_windows.go:178 +0x85
2024-03-13T09:32:50.9108418Z net.(*TCPListener).accept(0xc0000c0fc0)
2024-03-13T09:32:50.9108699Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock_posix.go:159 +0x3e
2024-03-13T09:32:50.9108819Z net.(*TCPListener).Accept(0xc0000c0fc0)
2024-03-13T09:32:50.9109066Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock.go:327 +0x65
2024-03-13T09:32:50.9109274Z net/http.(*Server).Serve(0xc0010f4f00, {0x14185a4f0, 0xc0000c0fc0})
2024-03-13T09:32:50.9109548Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/http/server.go:3255 +0x672
2024-03-13T09:32:50.9109676Z net/http/httptest.(*Server).goServe.func1()
2024-03-13T09:32:50.9109990Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/http/httptest/server.go:310 +0xbc
2024-03-13T09:32:50.9110257Z created by net/http/httptest.(*Server).goServe in goroutine 11787
2024-03-13T09:32:50.9110576Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/http/httptest/server.go:308 +0xa6
2024-03-13T09:32:50.9110583Z 
2024-03-13T09:32:50.9110709Z goroutine 11787 [chan receive, 4 minutes]:
2024-03-13T09:32:50.9110897Z testing.(*T).Run(0xc0006496c0, {0x14155274e, 0xf}, 0xc001995140)
2024-03-13T09:32:50.9111162Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1750 +0x851
2024-03-13T09:32:50.9111742Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.TestFilteredNotaryRequestSubscriptions(0xc0006496c0)
2024-03-13T09:32:50.9112066Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:403 +0x792
2024-03-13T09:32:50.9112183Z testing.tRunner(0xc0006496c0, 0x141678420)
2024-03-13T09:32:50.9112462Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1689 +0x21f
2024-03-13T09:32:50.9112583Z created by testing.(*T).Run in goroutine 1
2024-03-13T09:32:50.9112851Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1742 +0x826
2024-03-13T09:32:50.9112857Z 
2024-03-13T09:32:50.9112968Z goroutine 11791 [IO wait, 4 minutes]:
2024-03-13T09:32:50.9113112Z internal/poll.runtime_pollWait(0x4873f8b8, 0x72)
2024-03-13T09:32:50.9113381Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/netpoll.go:345 +0x85
2024-03-13T09:32:50.9113547Z internal/poll.(*pollDesc).wait(0xc000235840, 0x72, 0x0)
2024-03-13T09:32:50.9113887Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-13T09:32:50.9114029Z internal/poll.execIO(0xc0002356a0, 0xc000059930)
2024-03-13T09:32:50.9114341Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:175 +0x271
2024-03-13T09:32:50.9114636Z internal/poll.(*FD).acceptOne(0xc000235688, 0x364, {0xc0002f5b30, 0x2, 0x2}, 0xc0002356a0)
2024-03-13T09:32:50.9114947Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:944 +0xf8
2024-03-13T09:32:50.9115105Z internal/poll.(*FD).Accept(0xc000235688, 0xc0005afba8)
2024-03-13T09:32:50.9115461Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:978 +0x3cb
2024-03-13T09:32:50.9115565Z net.(*netFD).accept(0xc000235688)
2024-03-13T09:32:50.9115824Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/fd_windows.go:178 +0x85
2024-03-13T09:32:50.9115940Z net.(*TCPListener).accept(0xc0000c0f80)
2024-03-13T09:32:50.9116212Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock_posix.go:159 +0x3e
2024-03-13T09:32:50.9116322Z net.(*TCPListener).Accept(0xc0000c0f80)
2024-03-13T09:32:50.9116576Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock.go:327 +0x65
2024-03-13T09:32:50.9116783Z net/http.(*Server).Serve(0xc0010f4e10, {0x14185a4f0, 0xc0000c0f80})
2024-03-13T09:32:50.9117052Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/http/server.go:3255 +0x672
2024-03-13T09:32:50.9117421Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start.func1(0xc0010f4e10)
2024-03-13T09:32:50.9117668Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/server.go:403 +0x79
2024-03-13T09:32:50.9118088Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9118383Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/server.go:402 +0x1c5
2024-03-13T09:32:50.9118389Z 
2024-03-13T09:32:50.9118493Z goroutine 11793 [select, 4 minutes]:
2024-03-13T09:32:50.9118881Z github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).notificationDispatcher(0xc001a06608)
2024-03-13T09:32:50.9119109Z 	D:/a/neo-go/neo-go/pkg/core/blockchain.go:1336 +0x4b6
2024-03-13T09:32:50.9119476Z created by github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).Run in goroutine 11789
2024-03-13T09:32:50.9119694Z 	D:/a/neo-go/neo-go/pkg/core/blockchain.go:1071 +0x18b
2024-03-13T09:32:50.9119699Z 
2024-03-13T09:32:50.9119804Z goroutine 11811 [select, 4 minutes]:
2024-03-13T09:32:50.9120139Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).txHandlerLoop(0xc001923c08)
2024-03-13T09:32:50.9120354Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1155 +0x23c
2024-03-13T09:32:50.9120718Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9120935Z 	D:/a/neo-go/neo-go/pkg/network/server.go:291 +0x31c
2024-03-13T09:32:50.9120940Z 
2024-03-13T09:32:50.9121033Z goroutine 4724 [runnable]:
2024-03-13T09:32:50.9121527Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).notifySubscribers(0xc0007e6e00, {0xd4?, {0x0?, 0x0?}})
2024-03-13T09:32:50.9121842Z 	D:/a/neo-go/neo-go/pkg/rpcclient/wsclient.go:694 +0x172
2024-03-13T09:32:50.9122174Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*Internal).eventLoop(0xc0007e6e00)
2024-03-13T09:32:50.9122387Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:64 +0x47
2024-03-13T09:32:50.9122747Z created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewInternal in goroutine 4702
2024-03-13T09:32:50.9122958Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:45 +0x3cd
2024-03-13T09:32:50.9122963Z 
2024-03-13T09:32:50.9123089Z goroutine 11816 [chan receive, 4 minutes]:
2024-03-13T09:32:50.9123398Z github.com/nspcc-dev/neo-go/pkg/network/bqueue.(*Queue).Run(0xc00061a880)
2024-03-13T09:32:50.9123641Z 	D:/a/neo-go/neo-go/pkg/network/bqueue/queue.go:60 +0x9b
2024-03-13T09:32:50.9124006Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9124215Z 	D:/a/neo-go/neo-go/pkg/network/server.go:295 +0x557
2024-03-13T09:32:50.9124220Z 
2024-03-13T09:32:50.9124331Z goroutine 11815 [select, 4 minutes]:
2024-03-13T09:32:50.9124674Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).relayBlocksLoop(0xc001923c08)
2024-03-13T09:32:50.9124888Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1589 +0x225
2024-03-13T09:32:50.9125258Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9125467Z 	D:/a/neo-go/neo-go/pkg/network/server.go:294 +0x4ab
2024-03-13T09:32:50.9125472Z 
2024-03-13T09:32:50.9125595Z goroutine 11934 [chan receive, 4 minutes]:
2024-03-13T09:32:50.9126163Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.callWSGetRaw(0xc0011be340, 0xc0013f0000, {0xc0012d8240, 0x8a}, 0xc000b1fda0)
2024-03-13T09:32:50.9126513Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:47 +0x176
2024-03-13T09:32:50.9127092Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.callSubscribe(0xc0011be340, 0xc0013f0000, 0xc000b1fda0, {0xc00088a550, 0x4f})
2024-03-13T09:32:50.9127403Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:78 +0x115
2024-03-13T09:32:50.9127927Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.TestFilteredNotaryRequestSubscriptions.func5(0xc0011be340)
2024-03-13T09:32:50.9128240Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/subscription_test.go:404 +0xbf
2024-03-13T09:32:50.9128360Z testing.tRunner(0xc0011be340, 0xc001995140)
2024-03-13T09:32:50.9128640Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1689 +0x21f
2024-03-13T09:32:50.9128780Z created by testing.(*T).Run in goroutine 11787
2024-03-13T09:32:50.9129054Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/testing/testing.go:1742 +0x826
2024-03-13T09:32:50.9129059Z 
2024-03-13T09:32:50.9129192Z goroutine 11823 [select]:
2024-03-13T09:32:50.9129508Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).runProto(0xc001923c08)
2024-03-13T09:32:50.9129719Z 	D:/a/neo-go/neo-go/pkg/network/server.go:553 +0x229
2024-03-13T09:32:50.9130081Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).run in goroutine 11819
2024-03-13T09:32:50.9130291Z 	D:/a/neo-go/neo-go/pkg/network/server.go:453 +0x295
2024-03-13T09:32:50.9130296Z 
2024-03-13T09:32:50.9130420Z goroutine 11817 [chan receive, 4 minutes]:
2024-03-13T09:32:50.9130727Z github.com/nspcc-dev/neo-go/pkg/network/bqueue.(*Queue).Run(0xc00061a900)
2024-03-13T09:32:50.9130958Z 	D:/a/neo-go/neo-go/pkg/network/bqueue/queue.go:60 +0x9b
2024-03-13T09:32:50.9131325Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9131528Z 	D:/a/neo-go/neo-go/pkg/network/server.go:296 +0x605
2024-03-13T09:32:50.9131535Z 
2024-03-13T09:32:50.9131626Z goroutine 5768 [runnable]:
2024-03-13T09:32:50.9131963Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*Internal).eventLoop(0xc0007e6700)
2024-03-13T09:32:50.9132184Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:54 +0x194
2024-03-13T09:32:50.9132544Z created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewInternal in goroutine 5763
2024-03-13T09:32:50.9132746Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:45 +0x3cd
2024-03-13T09:32:50.9132822Z 
2024-03-13T09:32:50.9132930Z goroutine 11818 [IO wait, 4 minutes]:
2024-03-13T09:32:50.9133081Z internal/poll.runtime_pollWait(0x48b12d70, 0x72)
2024-03-13T09:32:50.9133353Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/runtime/netpoll.go:345 +0x85
2024-03-13T09:32:50.9133520Z internal/poll.(*pollDesc).wait(0xc0004ef340, 0x72, 0x0)
2024-03-13T09:32:50.9133860Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-03-13T09:32:50.9134001Z internal/poll.execIO(0xc0004ef1a0, 0xc000b799e0)
2024-03-13T09:32:50.9134316Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:175 +0x271
2024-03-13T09:32:50.9134624Z internal/poll.(*FD).acceptOne(0xc0004ef188, 0x344, {0xc001bb6000, 0x2, 0x2}, 0xc0004ef1a0)
2024-03-13T09:32:50.9134938Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:944 +0xf8
2024-03-13T09:32:50.9135103Z internal/poll.(*FD).Accept(0xc0004ef188, 0xc0013d1c58)
2024-03-13T09:32:50.9135421Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/internal/poll/fd_windows.go:978 +0x3cb
2024-03-13T09:32:50.9135519Z net.(*netFD).accept(0xc0004ef188)
2024-03-13T09:32:50.9135783Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/fd_windows.go:178 +0x85
2024-03-13T09:32:50.9135893Z net.(*TCPListener).accept(0xc001096240)
2024-03-13T09:32:50.9136171Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock_posix.go:159 +0x3e
2024-03-13T09:32:50.9136285Z net.(*TCPListener).Accept(0xc001096240)
2024-03-13T09:32:50.9136533Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/net/tcpsock.go:327 +0x65
2024-03-13T09:32:50.9136910Z github.com/nspcc-dev/neo-go/pkg/network.(*TCPTransport).Accept(0xc00025f650)
2024-03-13T09:32:50.9137162Z 	D:/a/neo-go/neo-go/pkg/network/tcp_transport.go:78 +0x448
2024-03-13T09:32:50.9137531Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9137752Z 	D:/a/neo-go/neo-go/pkg/network/server.go:298 +0x63d
2024-03-13T09:32:50.9137759Z 
2024-03-13T09:32:50.9137865Z goroutine 11813 [select, 4 minutes]:
2024-03-13T09:32:50.9138194Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).txHandlerLoop(0xc001923c08)
2024-03-13T09:32:50.9138416Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1155 +0x23c
2024-03-13T09:32:50.9138776Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9138989Z 	D:/a/neo-go/neo-go/pkg/network/server.go:291 +0x31c
2024-03-13T09:32:50.9138994Z 
2024-03-13T09:32:50.9139095Z goroutine 11790 [select, 4 minutes]:
2024-03-13T09:32:50.9139482Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleSubEvents(0xc000235408)
2024-03-13T09:32:50.9139786Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/server.go:2920 +0x86d
2024-03-13T09:32:50.9140196Z created by github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9140441Z 	D:/a/neo-go/neo-go/pkg/services/rpcsrv/server.go:390 +0xf4
2024-03-13T09:32:50.9140449Z 
2024-03-13T09:32:50.9140559Z goroutine 11810 [select, 4 minutes]:
2024-03-13T09:32:50.9140888Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).txHandlerLoop(0xc001923c08)
2024-03-13T09:32:50.9141105Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1155 +0x23c
2024-03-13T09:32:50.9141463Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9141670Z 	D:/a/neo-go/neo-go/pkg/network/server.go:291 +0x31c
2024-03-13T09:32:50.9141675Z 
2024-03-13T09:32:50.9141781Z goroutine 11812 [select, 4 minutes]:
2024-03-13T09:32:50.9142108Z github.com/nspcc-dev/neo-go/pkg/network.(*Server).txHandlerLoop(0xc001923c08)
2024-03-13T09:32:50.9142321Z 	D:/a/neo-go/neo-go/pkg/network/server.go:1155 +0x23c
2024-03-13T09:32:50.9142685Z created by github.com/nspcc-dev/neo-go/pkg/network.(*Server).Start in goroutine 11787
2024-03-13T09:32:50.9142892Z 	D:/a/neo-go/neo-go/pkg/network/server.go:291 +0x31c
2024-03-13T09:32:50.9142898Z 
2024-03-13T09:32:50.9143032Z goroutine 5078 [runnable]:
2024-03-13T09:32:50.9143210Z sync/atomic.(*Int32).Add(0xc0007e74b8, 0x40000000)
2024-03-13T09:32:50.9143483Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/sync/atomic/type.go:88 +0x56
2024-03-13T09:32:50.9143588Z sync.(*RWMutex).Unlock(0xc0007e74a8)
2024-03-13T09:32:50.9143841Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/sync/rwmutex.go:205 +0x5b
2024-03-13T09:32:50.9144330Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).notifySubscribers(0xc0007e7340, {0xd4?, {0x0?, 0x0?}})
2024-03-13T09:32:50.9144570Z 	D:/a/neo-go/neo-go/pkg/rpcclient/wsclient.go:706 +0x2f7
2024-03-13T09:32:50.9144905Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*Internal).eventLoop(0xc0007e7340)
2024-03-13T09:32:50.9145113Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:64 +0x47
2024-03-13T09:32:50.9145474Z created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewInternal in goroutine 5072
2024-03-13T09:32:50.9145684Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:45 +0x3cd
2024-03-13T09:32:50.9145691Z 
2024-03-13T09:32:50.9145790Z goroutine 5016 [runnable]:
2024-03-13T09:32:50.9145899Z sync/atomic.(*Value).Load(0xc00066ace8)
2024-03-13T09:32:50.9146176Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/sync/atomic/value.go:28 +0xf9
2024-03-13T09:32:50.9146289Z context.(*cancelCtx).Done(0xc00066acd0)
2024-03-13T09:32:50.9146557Z 	C:/hostedtoolcache/windows/go/1.22.1/x64/src/context/context.go:439 +0x50
2024-03-13T09:32:50.9146887Z github.com/nspcc-dev/neo-go/pkg/rpcclient.(*Internal).eventLoop(0xc0008b96c0)
2024-03-13T09:32:50.9147096Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:55 +0x73
2024-03-13T09:32:50.9147488Z created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewInternal in goroutine 5010
2024-03-13T09:32:50.9147704Z 	D:/a/neo-go/neo-go/pkg/rpcclient/local.go:45 +0x3cd
```

**Comment by AnnaShaleva** [comment]
Not exactly related to test timeout timeout, but sometimes the following errors occur:
```
2024-03-15T08:07:53.7689900Z === NAME  TestRPC/http/single_request/getstorage/invalid_key
2024-03-15T08:07:53.7690100Z     server_test.go:3463: 
2024-03-15T08:07:53.7691340Z         	Error Trace:	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server_test.go:3463
2024-03-15T08:07:53.7692540Z         	            				/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server_test.go:2517
2024-03-15T08:07:53.7692840Z         	Error:      	Received unexpected error:
2024-03-15T08:07:53.7693970Z         	            	Post "http://127.0.0.1:50228": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024-03-15T08:07:53.7694400Z         	Test:       	TestRPC/http/single_request/getstorage/invalid_key
2024-03-15T08:07:53.7694710Z         	Messages:   	could not make a POST request
```

**Comment by AnnaShaleva** [comment]
Not fixed, caught the following failure in #3380, ref. https://github.com/nspcc-dev/neo-go/pull/3380#issuecomment-2026779814:
```
2024-03-29T06:47:52.2085630Z === NAME  TestRPC/http/single_request/invokescript/positive,_good_witness
2024-03-29T06:47:52.2085840Z     server_test.go:3501: 
2024-03-29T06:47:52.2087050Z         	Error Trace:	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server_test.go:3501
2024-03-29T06:47:52.2088340Z         	            				/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/server_test.go:2519
2024-03-29T06:47:52.2088700Z         	Error:      	Received unexpected error:
2024-03-29T06:47:52.2089900Z         	            	Post "http://127.0.0.1:50203": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2024-03-29T06:47:52.2090720Z         	Test:       	TestRPC/http/single_request/invokescript/positive,_good_witness
2024-03-29T06:47:52.2091310Z         	Messages:   	could not make a POST request
```
