### ISSUE TITLE
`TestWalletImportDeployed` timed out on macOS

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2977]
[log.txt](https://github.com/nspcc-dev/neo-go/files/11248634/log.txt), go 1.20.

**Comment by AliceInHunterland** [comment]
got timeout in a different place, maybe related to this issue and to the #3300 

[Run tests (macos-12, 1.21)](https://github.com/nspcc-dev/neo-go/actions/runs/7961884377/job/21734075846#logs)

```
2024-02-19T15:41:17.5041590Z === NAME  TestClient_IteratorSessions/traverse,_concurrent_access
2024-02-19T15:41:17.5042790Z     client_test.go:1547: 
2024-02-19T15:41:17.5044180Z         	Error Trace:	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:1547
2024-02-19T15:41:17.5046200Z         	            				/Users/runner/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_amd64.s:1650
2024-02-19T15:41:17.5047400Z         	Error:      	Received unexpected error:
2024-02-19T15:41:17.5049410Z         	            	Post "http://127.0.0.1:49483": dial tcp 127.0.0.1:49483: connect: connection reset by peer
2024-02-19T15:41:17.5050940Z         	Test:       	TestClient_IteratorSessions/traverse,_concurrent_access
2024-02-19T15:41:17.5052050Z === NAME  TestClient_IteratorSessions

2024-02-19T15:41:17.5805740Z panic: test timed out after 10m0s
2024-02-19T15:41:17.5806000Z running tests:
2024-02-19T15:41:17.5806230Z 	TestClient_IteratorSessions (9m57s)
2024-02-19T15:41:17.5806640Z 	TestClient_IteratorSessions/traverse,_concurrent_access (9m57s)
2024-02-19T15:41:17.5806650Z 
2024-02-19T15:41:17.5806810Z goroutine 4483 [running]:
2024-02-19T15:41:17.5807010Z testing.(*M).startAlarm.func1()
2024-02-19T15:41:17.5807570Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:2259 +0x259
2024-02-19T15:41:17.5807740Z created by time.goFunc
2024-02-19T15:41:17.5808230Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/time/sleep.go:176 +0x45
2024-02-19T15:41:17.5808740Z 
2024-02-19T15:41:17.5808970Z goroutine 1 [chan receive, 9 minutes]:
2024-02-19T15:41:17.5809300Z testing.(*T).Run(0xc000182d00, {0x23fe760, 0x1b}, 0x2529d90)
2024-02-19T15:41:17.5810140Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1649 +0x871
2024-02-19T15:41:17.5810340Z testing.runTests.func1(0x0?)
2024-02-19T15:41:17.5810890Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:2054 +0x85
2024-02-19T15:41:17.5811110Z testing.tRunner(0xc000182d00, 0xc0002c1af8)
2024-02-19T15:41:17.5811690Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1595 +0x262
2024-02-19T15:41:17.5812460Z testing.runTests(0xc0001bc5a0?, {0x2fad5a0, 0x31, 0x31}, {0x1c?, 0x1e?, 0x2fb9660?})
2024-02-19T15:41:17.5813020Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:2052 +0x8ae
2024-02-19T15:41:17.5813200Z testing.(*M).Run(0xc0001bc5a0)
2024-02-19T15:41:17.5813740Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1925 +0xcd8
2024-02-19T15:41:17.5813890Z main.main()
2024-02-19T15:41:17.5814080Z 	_testmain.go:145 +0x2be
2024-02-19T15:41:17.5814090Z 
2024-02-19T15:41:17.5814310Z goroutine 2775 [chan receive, 9 minutes]:
2024-02-19T15:41:17.5814660Z testing.(*T).Run(0xc0069789c0, {0x23fe8a4, 0x1b}, 0xc00a3a4eb8)
2024-02-19T15:41:17.5815200Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1649 +0x871
2024-02-19T15:41:17.5815940Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.TestClient_IteratorSessions(0x0?)
2024-02-19T15:41:17.5816590Z 	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:1541 +0x94a
2024-02-19T15:41:17.5816800Z testing.tRunner(0xc0069789c0, 0x2529d90)
2024-02-19T15:41:17.5817350Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1595 +0x262
2024-02-19T15:41:17.5817570Z created by testing.(*T).Run in goroutine 1
2024-02-19T15:41:17.5818120Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1648 +0x846
2024-02-19T15:41:17.5818130Z 
2024-02-19T15:41:17.5818310Z goroutine 1367 [select, 9 minutes]:
2024-02-19T15:41:17.5818560Z net/http.(*persistConn).writeLoop(0xc002a597a0)
2024-02-19T15:41:17.5819330Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/transport.go:2421 +0x1bc
2024-02-19T15:41:17.5819700Z created by net/http.(*Transport).dialConn in goroutine 1364
2024-02-19T15:41:17.5820280Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/transport.go:1777 +0x266b
2024-02-19T15:41:17.5820290Z 
2024-02-19T15:41:17.5820480Z goroutine 1098 [IO wait, 9 minutes]:
2024-02-19T15:41:17.5820740Z internal/poll.runtime_pollWait(0xd38f008, 0x72)
2024-02-19T15:41:17.5821270Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/runtime/netpoll.go:343 +0x85
2024-02-19T15:41:17.5821630Z internal/poll.(*pollDesc).wait(0xc00321fa20, 0x10c9b01?, 0x0)
2024-02-19T15:41:17.5822290Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-02-19T15:41:17.5822500Z internal/poll.(*pollDesc).waitRead(...)
2024-02-19T15:41:17.5823110Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_poll_runtime.go:89
2024-02-19T15:41:17.5823320Z internal/poll.(*FD).Accept(0xc00321fa00)
2024-02-19T15:41:17.5823920Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_unix.go:611 +0x425
2024-02-19T15:41:17.5824100Z net.(*netFD).accept(0xc00321fa00)
2024-02-19T15:41:17.5824720Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/fd_unix.go:172 +0x3e
2024-02-19T15:41:17.5824930Z net.(*TCPListener).accept(0xc003df6ee0)
2024-02-19T15:41:17.5825480Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/tcpsock_posix.go:152 +0x3e
2024-02-19T15:41:17.5825690Z net.(*TCPListener).Accept(0xc003df6ee0)
2024-02-19T15:41:17.5826180Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/tcpsock.go:315 +0x65
2024-02-19T15:41:17.5826550Z net/http.(*Server).Serve(0xc0002a32c0, {0x2705410, 0xc003df6ee0})
2024-02-19T15:41:17.5827090Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/server.go:3056 +0x5e8
2024-02-19T15:41:17.5827320Z net/http/httptest.(*Server).goServe.func1()
2024-02-19T15:41:17.5827940Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/httptest/server.go:310 +0xd0
2024-02-19T15:41:17.5828430Z created by net/http/httptest.(*Server).goServe in goroutine 1093
2024-02-19T15:41:17.5829050Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/httptest/server.go:308 +0xa6
2024-02-19T15:41:17.5829060Z 
2024-02-19T15:41:17.5829250Z goroutine 119 [IO wait, 9 minutes]:
2024-02-19T15:41:17.5829510Z internal/poll.runtime_pollWait(0xd255668, 0x72)
2024-02-19T15:41:17.5830040Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/runtime/netpoll.go:343 +0x85
2024-02-19T15:41:17.5830530Z internal/poll.(*pollDesc).wait(0xc0001113a0, 0x10c9b01?, 0x0)
2024-02-19T15:41:17.5831210Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-02-19T15:41:17.5831420Z internal/poll.(*pollDesc).waitRead(...)
2024-02-19T15:41:17.5832020Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_poll_runtime.go:89
2024-02-19T15:41:17.5832230Z internal/poll.(*FD).Accept(0xc000111380)
2024-02-19T15:41:17.5832840Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_unix.go:611 +0x425
2024-02-19T15:41:17.5833020Z net.(*netFD).accept(0xc000111380)
2024-02-19T15:41:17.5833640Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/fd_unix.go:172 +0x3e
2024-02-19T15:41:17.5833890Z net.(*TCPListener).accept(0xc0002266c0)
2024-02-19T15:41:17.5842440Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/tcpsock_posix.go:152 +0x3e
2024-02-19T15:41:17.5842730Z net.(*TCPListener).Accept(0xc0002266c0)
2024-02-19T15:41:17.5843250Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/tcpsock.go:315 +0x65
2024-02-19T15:41:17.5843630Z net/http.(*Server).Serve(0xc0002a23c0, {0x2705410, 0xc0002266c0})
2024-02-19T15:41:17.5844180Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/server.go:3056 +0x5e8
2024-02-19T15:41:17.5844410Z net/http/httptest.(*Server).goServe.func1()
2024-02-19T15:41:17.5845040Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/httptest/server.go:310 +0xd0
2024-02-19T15:41:17.5845800Z created by net/http/httptest.(*Server).goServe in goroutine 92
2024-02-19T15:41:17.5846430Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/httptest/server.go:308 +0xa6
2024-02-19T15:41:17.5846440Z 
2024-02-19T15:41:17.5846650Z goroutine 2893 [semacquire, 9 minutes]:
2024-02-19T15:41:17.5846860Z sync.runtime_Semacquire(0xc00a402f68?)
2024-02-19T15:41:17.5847360Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/runtime/sema.go:62 +0x25
2024-02-19T15:41:17.5847560Z sync.(*WaitGroup).Wait(0xc00a402f60)
2024-02-19T15:41:17.5848090Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/sync/waitgroup.go:116 +0xa5
2024-02-19T15:41:17.5849010Z github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.TestClient_IteratorSessions.func6(0xc004751d40)
2024-02-19T15:41:17.5849650Z 	/Users/runner/work/neo-go/neo-go/pkg/services/rpcsrv/client_test.go:1554 +0x2ea
2024-02-19T15:41:17.5849870Z testing.tRunner(0xc004751d40, 0xc00a3a4eb8)
2024-02-19T15:41:17.5850420Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1595 +0x262
2024-02-19T15:41:17.5850670Z created by testing.(*T).Run in goroutine 2775
2024-02-19T15:41:17.5851220Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/testing/testing.go:1648 +0x846
2024-02-19T15:41:17.5851230Z 
2024-02-19T15:41:17.5851420Z goroutine 901 [IO wait, 9 minutes]:
2024-02-19T15:41:17.5852020Z internal/poll.runtime_pollWait(0xd38f100, 0x72)
2024-02-19T15:41:17.5852610Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/runtime/netpoll.go:343 +0x85
2024-02-19T15:41:17.5852990Z internal/poll.(*pollDesc).wait(0xc000f47ba0, 0xc002b34000?, 0x0)
2024-02-19T15:41:17.5853660Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-02-19T15:41:17.5853870Z internal/poll.(*pollDesc).waitRead(...)
2024-02-19T15:41:17.5854480Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_poll_runtime.go:89
2024-02-19T15:41:17.5854880Z internal/poll.(*FD).Read(0xc000f47b80, {0xc002b34000, 0x1000, 0x1000})
2024-02-19T15:41:17.5855490Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_unix.go:164 +0x405
2024-02-19T15:41:17.5855970Z net.(*netFD).Read(0xc000f47b80, {0xc002b34000, 0x1000, 0x1000})
2024-02-19T15:41:17.5856470Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/fd_posix.go:55 +0x4b
2024-02-19T15:41:17.5856800Z net.(*conn).Read(0xc0000e4630, {0xc002b34000, 0x1000, 0x1000})
2024-02-19T15:41:17.5857250Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/net.go:179 +0xad
2024-02-19T15:41:17.5857690Z net/http.(*connReader).Read(0xc0017e08a0, {0xc002b34000, 0x1000, 0x1000})
2024-02-19T15:41:17.5858410Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/server.go:791 +0x2b2
2024-02-19T15:41:17.5858610Z bufio.(*Reader).fill(0xc002b320c0)
2024-02-19T15:41:17.5859110Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/bufio/bufio.go:113 +0x29a
2024-02-19T15:41:17.5859310Z bufio.(*Reader).Peek(0xc002b320c0, 0x4)
2024-02-19T15:41:17.5859800Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/bufio/bufio.go:151 +0xc7
2024-02-19T15:41:17.5860150Z net/http.(*conn).serve(0xc002b2b4d0, {0x2707850, 0xc00179a180})
2024-02-19T15:41:17.5860710Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/server.go:2044 +0xe7c
2024-02-19T15:41:17.5861000Z created by net/http.(*Server).Serve in goroutine 965
2024-02-19T15:41:17.5861550Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/server.go:3086 +0x86d
2024-02-19T15:41:17.5861560Z 
2024-02-19T15:41:17.5861750Z goroutine 1550 [select, 9 minutes]:
2024-02-19T15:41:17.5862010Z net/http.(*persistConn).writeLoop(0xc000e1f440)
2024-02-19T15:41:17.5862600Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/transport.go:2421 +0x1bc
2024-02-19T15:41:17.5862950Z created by net/http.(*Transport).dialConn in goroutine 1547
2024-02-19T15:41:17.5863540Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/transport.go:1777 +0x266b
2024-02-19T15:41:17.5863550Z 
2024-02-19T15:41:17.5863730Z goroutine 231 [IO wait, 9 minutes]:
2024-02-19T15:41:17.5863990Z internal/poll.runtime_pollWait(0xd255570, 0x72)
2024-02-19T15:41:17.5864690Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/runtime/netpoll.go:343 +0x85
2024-02-19T15:41:17.5865070Z internal/poll.(*pollDesc).wait(0xc000f9e920, 0xc000b81000?, 0x0)
2024-02-19T15:41:17.5865740Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
2024-02-19T15:41:17.5866040Z internal/poll.(*pollDesc).waitRead(...)
2024-02-19T15:41:17.5866660Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_poll_runtime.go:89
2024-02-19T15:41:17.5867070Z internal/poll.(*FD).Read(0xc000f9e900, {0xc000b81000, 0x1000, 0x1000})
2024-02-19T15:41:17.5867680Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/internal/poll/fd_unix.go:164 +0x405
2024-02-19T15:41:17.5868010Z net.(*netFD).Read(0xc000f9e900, {0xc000b81000, 0x1000, 0x1000})
2024-02-19T15:41:17.5868510Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/fd_posix.go:55 +0x4b
2024-02-19T15:41:17.5868830Z net.(*conn).Read(0xc0003da010, {0xc000b81000, 0x1000, 0x1000})
2024-02-19T15:41:17.5869280Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/net.go:179 +0xad
2024-02-19T15:41:17.5869720Z net/http.(*persistConn).Read(0xc000ca2480, {0xc000b81000, 0x1000, 0x1000})
2024-02-19T15:41:17.5870290Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/transport.go:1954 +0x105
2024-02-19T15:41:17.5871180Z bufio.(*Reader).fill(0xc000ccc000)
2024-02-19T15:41:17.5871730Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/bufio/bufio.go:113 +0x29a
2024-02-19T15:41:17.5871940Z bufio.(*Reader).Peek(0xc000ccc000, 0x1)
2024-02-19T15:41:17.5872440Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/bufio/bufio.go:151 +0xc7
2024-02-19T15:41:17.5872680Z net/http.(*persistConn).readLoop(0xc000ca2480)
2024-02-19T15:41:17.5873260Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/transport.go:2118 +0x354
2024-02-19T15:41:17.5873600Z created by net/http.(*Transport).dialConn in goroutine 247
2024-02-19T15:41:17.5874190Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/transport.go:1776 +0x25da
2024-02-19T15:41:17.5874210Z 
2024-02-19T15:41:17.5874650Z goroutine 357 [select, 9 minutes]:
2024-02-19T15:41:17.5874920Z net/http.(*persistConn).writeLoop(0xc000b93440)
2024-02-19T15:41:17.5875490Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/transport.go:2421 +0x1bc
2024-02-19T15:41:17.5875840Z created by net/http.(*Transport).dialConn in goroutine 387
2024-02-19T15:41:17.5876420Z 	/Users/runner/hostedtoolcache/go/1.21.6/x64/src/net/http/transport.go:1777 +0x266b
2024-02-19T15:41:17.5876430Z 
```

[5_Run tests.txt](https://github.com/nspcc-dev/neo-go/files/14334404/5_Run.tests.txt)

**Comment by AliceInHunterland** [comment]
logs show only ~120ms from 10 min run.. and as for `TestWalletImportDeployed` itself it took only 8s before interrupting by test timeout (as indicated in logs:
`TestWalletImportDeployed (8s)`) which is normal. so the problem wasn't with this particular test.  But in the package `github.com/nspcc-dev/neo-go/cli/wallet	600.873s`, normal time now in the master is 216.852s - 417.511s.
Probably it could be a slow mac gh runner/ race in the network (something like #3307) / situation similar to https://github.com/nspcc-dev/neo-go/issues/2868 -aslo havent seen it for a long time / something else. @AnnaShaleva any ideas about it?

**Comment by AnnaShaleva** [comment]
We need this test to be reproduced on the current master. I've checked the goroutines trace and I don't see any clue on the reason of time out. There's no goroutine that is waiting for some event. The only suspicious for me is goroutine performing key decryption, but it can't take 10m:
```
2023-04-17T06:56:02.7213370Z goroutine 2057 [runnable]:
2023-04-17T06:56:02.7213760Z golang.org/x/crypto/scrypt.salsaXOR(0xc000ee13a8, {0xc000f9c700, 0x40, 0x40?}, {0xc000f9c180, 0x1a0, 0x1a0?})
2023-04-17T06:56:02.7214170Z 	/Users/runner/go/pkg/mod/golang.org/x/crypto@v0.4.0/scrypt/scrypt.go:35 +0x11d8
2023-04-17T06:56:02.7214540Z golang.org/x/crypto/scrypt.blockMix(0xc000ee13a8, {0xc000f9c400, 0x100, 0x100}, {0xc000f9c000, 0x200, 0x200}, 0x8)
2023-04-17T06:56:02.7214930Z 	/Users/runner/go/pkg/mod/golang.org/x/crypto@v0.4.0/scrypt/scrypt.go:135 +0x24f
2023-04-17T06:56:02.7215350Z golang.org/x/crypto/scrypt.smix({0xc000eea800, 0x1800, 0x1800}, 0x8, 0x4000, {0xc001a84000, 0x400000, 0x400000}, {0xc000f9c000, 0x200, ...})
2023-04-17T06:56:02.7215720Z 	/Users/runner/go/pkg/mod/golang.org/x/crypto@v0.4.0/scrypt/scrypt.go:170 +0x535
2023-04-17T06:56:02.7216070Z golang.org/x/crypto/scrypt.Key({0xc000f84568, 0x4, 0x8}, {0xc0001b9720, 0x4, 0x20}, 0x4000, 0x8, 0x8, 0x40)
2023-04-17T06:56:02.7216450Z 	/Users/runner/go/pkg/mod/golang.org/x/crypto@v0.4.0/scrypt/scrypt.go:208 +0x36b
2023-04-17T06:56:02.7217200Z github.com/nspcc-dev/neo-go/pkg/crypto/keys.NEP2Encrypt(0xc000f983c0, {0xc000f84529, 0x4}, {0xc000d06b48?, 0x10c7685?, 0x4?})
2023-04-17T06:56:02.7217700Z 	/Users/runner/work/neo-go/neo-go/pkg/crypto/keys/nep2.go:52 +0x1d7
2023-04-17T06:56:02.7218830Z github.com/nspcc-dev/neo-go/pkg/wallet.(*Account).Encrypt(0xc000939920, {0xc000f84529, 0x4}, {0x1?, 0x1?, 0x1065842?})
2023-04-17T06:56:02.7219230Z 	/Users/runner/work/neo-go/neo-go/pkg/wallet/account.go:173 +0x87
2023-04-17T06:56:02.7219690Z github.com/nspcc-dev/neo-go/cli/wallet.newAccountFromWIF({0x279df60, 0xc00060c540}, {0xc000d302c0, 0x34}, {0x16353df?, 0x10c7685?, 0x11b98d7?}, 0x0, 0x0)
2023-04-17T06:56:02.7220000Z 	/Users/runner/work/neo-go/neo-go/cli/wallet/wallet.go:1040 +0x6c5
2023-04-17T06:56:02.7220300Z github.com/nspcc-dev/neo-go/cli/wallet.importDeployed(0xc000d01600)
2023-04-17T06:56:02.7220590Z 	/Users/runner/work/neo-go/neo-go/cli/wallet/wallet.go:584 +0x4fd
2023-04-17T06:56:02.7220760Z github.com/urfave/cli.HandleAction({0x22c7be0?, 0x25ce8d0?}, 0xf?)
2023-04-17T06:56:02.7220960Z 	/Users/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x78
2023-04-17T06:56:02.7221180Z github.com/urfave/cli.Command.Run({{0x24845dd, 0xf}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x24904d4, 0x18}, {0x24ce12c, ...}, ...}, ...)
2023-04-17T06:56:02.7221390Z 	/Users/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0xc78
2023-04-17T06:56:02.7221570Z github.com/urfave/cli.(*App).RunAsSubcommand(0xc000f86000, 0xc000d01340)
2023-04-17T06:56:02.7221780Z 	/Users/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x1b65
2023-04-17T06:56:02.7222000Z github.com/urfave/cli.Command.startApp({{0x247adf7, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x24a2b4c, 0x24}, {0x0, ...}, ...}, ...)
2023-04-17T06:56:02.7222210Z 	/Users/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x1805
2023-04-17T06:56:02.7222410Z github.com/urfave/cli.Command.Run({{0x247adf7, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x24a2b4c, 0x24}, {0x0, ...}, ...}, ...)
2023-04-17T06:56:02.7222620Z 	/Users/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0xf05
2023-04-17T06:56:02.7222780Z github.com/urfave/cli.(*App).Run(0xc0000e9340, {0xc00098a840, 0xb, 0xb})
2023-04-17T06:56:02.7222990Z 	/Users/runner/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0xfa5
2023-04-17T06:56:02.7223350Z github.com/nspcc-dev/neo-go/internal/testcli.(*Executor).run(0xc00061e800, {0xc00098a840, 0xb, 0xb})
2023-04-17T06:56:02.7223670Z 	/Users/runner/work/neo-go/neo-go/internal/testcli/executor.go:287 +0x3ba
2023-04-17T06:56:02.7224510Z github.com/nspcc-dev/neo-go/internal/testcli.(*Executor).RunWithError(0xc000a421e0?, 0x247bb83?, {0xc00098a840, 0xb, 0xb})
2023-04-17T06:56:02.7224880Z 	/Users/runner/work/neo-go/neo-go/internal/testcli/executor.go:270 +0x110
2023-04-17T06:56:02.7225230Z github.com/nspcc-dev/neo-go/cli/wallet_test.TestWalletImportDeployed.func6(0x0?)
2023-04-17T06:56:02.7225540Z 	/Users/runner/work/neo-go/neo-go/cli/wallet/wallet_test.go:648 +0x72b
2023-04-17T06:56:02.7225670Z testing.tRunner(0xc00027d1e0, 0xc0008fb110)
2023-04-17T06:56:02.7225880Z 	/Users/runner/hostedtoolcache/go/1.20.3/x64/src/testing/testing.go:1576 +0x217
2023-04-17T06:56:02.7225990Z created by testing.(*T).Run
2023-04-17T06:56:02.7226200Z 	/Users/runner/hostedtoolcache/go/1.20.3/x64/src/testing/testing.go:1629 +0x806
```

Need to wait for this timeout to be reproduced.

**Comment by AnnaShaleva** [comment]
I'm closing this issue as stale, if it's reproduced on a fresh master, then need to add fresh logs/traces and investigate.
