### ISSUE TITLE
.docker: Nodes panicked on env restart 

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#2984]
I'm running `make env_up` command for test purposes. I needed to restart the environment without cleaning, but encountered following panic:
```go
$ docker logs neo_go_node_one
=> Try to restore blocks before running node
2023-04-21T06:42:39.743Z	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
2023-04-21T06:42:39.743Z	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2023-04-21T06:42:39.743Z	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2023-04-21T06:42:39.743Z	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2023-04-21T06:42:39.743Z	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2023-04-21T06:42:39.743Z	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 86400}
2023-04-21T06:42:39.743Z	INFO	Hardforks are not set, using default value
2023-04-21T06:42:39.745Z	INFO	restoring blockchain	{"version": "0.2.8"}
panic: item with id = -10 and key = 0a is not initialized

goroutine 1 [running]:
github.com/nspcc-dev/neo-go/pkg/core/native.getIntWithKey(0xa5aaf7?, 0xc0002ba180?, {0x18ae2aa, 0x1, 0xc000293ed8?})
	github.com/nspcc-dev/neo-go/pkg/core/native/util.go:46 +0x19b
github.com/nspcc-dev/neo-go/pkg/core/native.(*Notary).InitializeCache(0xc00019fa00, 0xc00029e190?)
	github.com/nspcc-dev/neo-go/pkg/core/native/notary.go:157 +0x45
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).initializeNativeCache(0xc000598900, 0x3915?, 0x1?)
	github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:899 +0x15d
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).init(0xc000598900)
	github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:467 +0x648
github.com/nspcc-dev/neo-go/pkg/core.NewBlockchain({0x123df98?, 0xc00028c0a8}, {{0x0, 0x0, 0xddb1, 0xc350, 0xc0002f4870, 0x12795f58d50000, 0x3e8, 0x0, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:323 +0x191b
github.com/nspcc-dev/neo-go/cli/server.initBlockChain({{0x0, 0x0, 0xddb1, 0xc350, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/cli/server/server.go:661 +0x245
github.com/nspcc-dev/neo-go/cli/server.initBCWithMetrics({{0x0, 0x0, 0xddb1, 0xc350, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/cli/server/server.go:135 +0x57
github.com/nspcc-dev/neo-go/cli/server.startServer(0xc000482160)
	github.com/nspcc-dev/neo-go/cli/server/server.go:454 +0x53c
github.com/urfave/cli.HandleAction({0xe4c020?, 0x11059e0?}, 0x4?)
	github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0xfd22f3, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xfe10cc, 0x12}, {0x100721b, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc0002e4000, {0xc00003a140, 0x5, 0x5})
	github.com/urfave/cli@v1.22.5/app.go:277 +0x8a7
main.main()
	./main.go:12 +0x33
```

Same for other 3 nodes.

That happened to me for the 1st time, earlier I restared env normally.

Version: e29c33e449bfca6b9481da4e9c2e5a2d40881dec
DB: [neo_go_node_one_db.tar.gz](https://github.com/nspcc-dev/neo-go/files/11293090/neo_go_node_one_db.tar.gz)
Config:
```yaml
ProtocolConfiguration:
  Magic: 56753
  MaxTraceableBlocks: 200000
  TimePerBlock: 1s
  MemPoolSize: 50000
  StandbyCommittee:
    - 02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2
    - 02103a7f7dd016558597f7960d27c516a4394fd968b9e65155eb4b013e4040406e
    - 03d90c07df63e690ce77912e10ab51acc944b66860237b608c4f8f8309e71ee699
    - 02a7bc55fe8684e0119768d104ba30795bdcc86619e864add26156723ed185cd62
  ValidatorsCount: 4
  SeedList:
    - node_one:20333
    - node_two:20334
    - node_three:20335
    - node_four:20336
  VerifyTransactions: true
  P2PSigExtensions: true
  NativeActivations:
    ContractManagement: [0]
    StdLib: [0]
    CryptoLib: [0]
    LedgerContract: [0]
    NeoToken: [0]
    GasToken: [0]
    PolicyContract: [0]
    RoleManagement: [0]
    OracleContract: [0]

ApplicationConfiguration:
  SkipBlockVerification: false
  # LogPath could be set up in case you need stdout logs to some proper file.
  # LogPath: "./log/neogo.log"
  DBConfiguration:
    Type: "leveldb" #other options: 'inmemory','boltdb'
    # DB type options. Uncomment those you need in case you want to switch DB type.
    LevelDBOptions:
      DataDirectoryPath: "/chains/one"
  #    BoltDBOptions:
  #      FilePath: "./chains/privnet.bolt"
  P2P:
    Addresses:
      - ":20333" # in form of "[host]:[port][:announcedPort]"
    DialTimeout: 3s
    ProtoTickInterval: 2s
    PingInterval: 30s
    PingTimeout: 90s
    MaxPeers: 10
    AttemptConnPeers: 5
    MinPeers: 2
  Relay: true
  Oracle:
    Enabled: false
    AllowedContentTypes:
      - application/json
    Nodes:
      - http://node_one:30333
      - http://node_two:30334
      - http://node_three:30335
      - http://node_four:30336
    RequestTimeout: 5s
    UnlockWallet:
      Path: "/wallet1.json"
      Password: "one"
  P2PNotary:
    Enabled: true
    UnlockWallet:
      Path: "/wallet1.json"
      Password: "one"
  RPC:
    Enabled: true
    Addresses:
      - ":30333"
    MaxGasInvoke: 15
    EnableCORSWorkaround: false
  Prometheus:
    Enabled: true
    Addresses:
      - ":20001"
  Pprof:
    Enabled: false
    Port: 20011
  Consensus:
    Enabled: true
    UnlockWallet:
      Path: "/wallet1.json"
      Password: "one"
```

**Comment by roman-khimov** [comment]
Cache initialization should be dependent on `NativeActivations`.
