### ISSUE TITLE
NPE in WebSocket client subscriptions

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#3093]
caught suddenly while debugging https://github.com/nspcc-dev/neofs-node/pull/2444, don’t have a special context. I subscribe to new blocks and notary requests
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7bc119]

goroutine 14 [running]:
github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).notifySubscribers(0xc000224480, {0x16?, {0xa11180?, 0xc000283ea0?}})
	/home/ll/go/pkg/mod/github.com/nspcc-dev/neo-go@v0.101.1/pkg/rpcclient/wsclient.go:599 +0x299
github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).wsReader(0xc000224480)
	/home/ll/go/pkg/mod/github.com/nspcc-dev/neo-go@v0.101.1/pkg/rpcclient/wsclient.go:513 +0x545
created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewWS
	/home/ll/go/pkg/mod/github.com/nspcc-dev/neo-go@v0.101.1/pkg/rpcclient/wsclient.go:422 +0x638
```

may be i violated some strict requirement on my side, but didn't find it after a quick look

**Comment by AnnaShaleva** [comment]
The issue is caused by the fact that `subscriptions` map of WS client isn't in sync with `receivers` map (although it always must be). And currently I can't find where the bug is and also can't reproduce the panic. It's possible that concurrency issue occurs between subsequent event receiving and unsubscription.

**Comment by carpawell** [comment]
100ms long blocks make it fail often.

**Comment by carpawell** [comment]
@roman-khimov, @AnnaShaleva, @AliceInHunterland, there is some race-by-design currently and I am not sure what can be done here (mostly because I want to make a fix small and reliable, no big changes). The key reason is that the subscription lock is always taken _after RPC is done_, (e.g. https://github.com/nspcc-dev/neo-go/blob/f0ae14e4db9c26da2ee5686e51edf4c248647ce3/pkg/rpcclient/wsclient.go#L774-L779) and it cannot control the sequence of the client's call.

This became an often issue when we started to wait for some TXs in our test runs: https://github.com/nspcc-dev/neofs-node/blob/24fc815cd4b262b625e24bac62259325aba3444c/pkg/morph/client/meta.go#L32 cause it uses subscriptions per every call: https://github.com/nspcc-dev/neo-go/blob/f0ae14e4db9c26da2ee5686e51edf4c248647ce3/pkg/rpcclient/waiter/waiter.go#L247-L260 (per every object put which can be often and can be concurrent).

Every client's (Un)Subscription call does two things: an RPC call and a subscription map lock (two of maps currently). If we imagine that there is one routine that tries to subscribe (A) and one routine that tries to unsubscribe (B), the following sequence can happen:

0. Current number of subscriptions is X
1. B does an RPC and makes number of subscriptions X-1
2. A does an RPC and makes number of subscriptions X again
3. A holds subscription locks and rewrites client's subscription state (subscription with ID X now points to a different channel; channel that was registered by B is lost and is not related to any real subscription but is still included in the `receivers` map)
4. B holds subscription locks and drops subscription X (first, it is an error and we have just lost a subscription that we think was made successfully second, we have lost a channel in the `receivers` map, and no corresponding subscription points to it)
5. X subscription is received by the WS client (in practice it is a new block, 100ms, quite often to be sure this issue happens every hour), we range through the `receivers`, see no corresponding subscription, and panic: https://github.com/nspcc-dev/neo-go/blob/f0ae14e4db9c26da2ee5686e51edf4c248647ce3/pkg/rpcclient/wsclient.go#L696

### 1
The easiest solution is to put subscription RPC inside `Lock`/`Unlock` space so no conflicts will ever happen. but I am not sure this is what is expected to be done and also performance may decrease (but it seems a real solution that fits the current design with non-monotonic subscription IDs).

### 2
The second idea is to make the subscription ID be smth like the request ID (the later subscription call is made the bigger its ID is _always_). I am not sure it may happen, cause there is some logic about the subscription numbers: https://github.com/nspcc-dev/neo-go/blob/f0ae14e4db9c26da2ee5686e51edf4c248647ce3/pkg/services/rpcsrv/server.go#L2776-L2799

### 3
Also, I think it is possible to make every subscription completely unique and not be a simple number. This may be some hash or time-dependent thing, or requests-dependent, is not important, it just has to be unique for every subscription and has to make conflicts impossible.

____

Thoughts?

**Comment by roman-khimov** [comment]
Server can return any IDs it wants and client has to live with that, so any server-side "fix" is not appropriate.

Simple lock extension can affect event processing since it has to access the same map as well. What we need in fact is to have the same order of event as we have on the server. And it's not a simple thing since two concurrent requests can be server in any order by the server. Still, we do have some order in `wsReader`, we just need to leverage it.

**Comment by roman-khimov** [comment]
The other idea is to fetch the subscriber before `unsubscribe` and compare current one with it after the request, if it's the old one --- drop it, if it's something else --- OK, we're not touching it. Subscription always overwrites values anyway and that's correct.

**Comment by AnnaShaleva** [comment]
The same panic occurs on 0.108.2+ node, although the reason leading to this panic may be different this time:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xbb43ec]
goroutine 74 [running]:
github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).notifySubscribers(0xc001503180, {0x9c?, {0x10e36a0?, 0xc00460c640?}})
	github.com/nspcc-dev/neo-go@v0.108.2-0.20250414115617-823a05fcc10b/pkg/rpcclient/wsclient.go:701 +0x26c
github.com/nspcc-dev/neo-go/pkg/rpcclient.(*WSClient).wsReader(0xc001503180)
	github.com/nspcc-dev/neo-go@v0.108.2-0.20250414115617-823a05fcc10b/pkg/rpcclient/wsclient.go:592 +0x5e5
created by github.com/nspcc-dev/neo-go/pkg/rpcclient.NewWS in goroutine 1
	github.com/nspcc-dev/neo-go@v0.108.2-0.20250414115617-823a05fcc10b/pkg/rpcclient/wsclient.go:493 +0x4f9
```

@carpawell, can you provide some more details about the steps which lead to this panic?

**Comment by carpawell** [comment]
Conditions were pretty the same as in the initial problem: 100ms blocks, fast network, and at least one local client for subscriptions (and a few remote in terms of the network). We have a mistake that leads us to subscribing and unsubscribing quite often: we use [waiter](https://github.com/nspcc-dev/neo-go/blob/9e8100ab5db4e37534014d0a7f159485635ae1ac/pkg/rpcclient/waiter/waiter.go#L278-L290) for every object, and objects were put really often with _number_ of threads per every node. There was also some connection loss (closing channels in neo-go's terms) and limiting subscriptions messages (`"maximum number of subscriptions is reached"`).

**Comment by AnnaShaleva** [comment]
> Conditions were pretty the same as in the initial problem

Could you provide a branch/revision of NeoFS node or devnet and steps to setup the described scenario so that I can run exactly *your* environment where you faced the problem?

**Comment by roman-khimov** [comment]
Copilot.

> I'll fix the panic in the notifySubscribers method. Based on the stack trace, there's a nil pointer dereference happening at line 701. Let's analyze and fix the issue.

> Looking at the code, the issue is likely in the notifySubscribers function, where it's accessing a subscription from the subscriptions map without checking if it exists. If an ID is present in the receivers map but the corresponding subscription has been removed from the subscriptions map, it would lead to a nil pointer dereference.

> Let me add a check to ensure the subscription exists before trying to use it:
```
diff --git a/pkg/rpcclient/wsclient.go b/pkg/rpcclient/wsclient.go
index 887e6aa59..8f42de16d 100644
--- a/pkg/rpcclient/wsclient.go
+++ b/pkg/rpcclient/wsclient.go
@@ -701,7 +701,12 @@ func (c *WSClient) notifySubscribers(ntf Notification) {
        c.subscriptionsLock.Lock()
        for rcvrCh, ids := range c.receivers {
                for _, id := range ids {
-                       ok, dropCh := c.subscriptions[id].TrySend(ntf, c.wsOpts.CloseNotificationChannelIfFull)
+                       // Check if subscription exists before trying to use it
+                       subscription, exists := c.subscriptions[id]
+                       if !exists {
+                               continue
+                       }
+                       ok, dropCh := subscription.TrySend(ntf, c.wsOpts.CloseNotificationChannelIfFull)
                        if dropCh {
                                c.dropSubCh(rcvrCh, id, false)
                                break // strictly single drop per channel
```

**Comment by roman-khimov** [comment]
My options would be:

1. Total ordering of subscription/unsubscription client-side. Just like it is this way server-side (not intentionally, but due to the way WS requests are processed). Have a routine managing this, push requests to it via channel, get response back. One at a time.
2. Or speculative removal from `c.subscriptions` when doing `performUnsubscription` (before network request). This would require ignoring events from this channel if they happen, but would effectively do the same as 1 (because of locks). The problem is sub/unsub mix.

`rcvrWas.Receiver() != rcvr.Receiver()` is not very reliable, btw.

**Comment by roman-khimov** [comment]
Or it all can be handled in `wsReader()` which is kinda 1.

**Comment by carpawell** [comment]
> Could you provide a branch/revision of NeoFS node or devnet and steps to setup the described scenario so that I can run exactly your environment where you faced the problem?

I do believe it does not matter. neo-go's hash is known, and then just subscribe and unsubscribe using up to 3*20 threads (can be sending some txs and `WaitSuccess` for them) via local client. It was internal testing, I did not create this VMs. If you need some close condition, it can be https://github.com/nspcc-dev/neofs-dev-env/pull/330 with 100ms blocks smwh [here](https://github.com/carpawell/neofs-dev-env/blob/170a4a70130d8991dc2e065b5c222a181ac72363/services/ir1/cfg/config.yml#L42) and then smth like `neofs-cli container create -r s01.neofs.devenv:8080 --policy 'REP 4' -w services/chain/node-wallet.json --basic-acl public-read --await --attributes "__NEOFS__METAINFO_CONSISTENCY=strict"` and putting objects with many threads.
