### ISSUE TITLE
Compiler dies when sees cycled imports

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neo-go#3202]
## Current Behavior
```
▶ make archive  
/home/carpawell/NSPCC/git/neofs-contract/bin/cli contract compile -i alphabet -c alphabet/config.yml -m alphabet/config.json -o alphabet/alphabet_contract.nef --bindings alphabet/bindings_config.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xeec384]

goroutine 1 [running]:
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).visitPkg(0xc0003f54a0, 0x0, 0xc000404b11?)
        github.com/nspcc-dev/neo-go@v0.103.1/pkg/compiler/analysis.go:281 +0x24
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).visitPkg(0xc0003f54a0, 0xc000433c80, 0xc000404780?)
        github.com/nspcc-dev/neo-go@v0.103.1/pkg/compiler/analysis.go:285 +0xa7
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).visitPkg(0xc0003f54a0, 0xc000434c00, 0xc000404900?)
        github.com/nspcc-dev/neo-go@v0.103.1/pkg/compiler/analysis.go:285 +0xa7
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).visitPkg(0xc0003f54a0, 0xc000438300, 0x0?)
        github.com/nspcc-dev/neo-go@v0.103.1/pkg/compiler/analysis.go:285 +0xa7
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).analyzePkgOrder(...)
        github.com/nspcc-dev/neo-go@v0.103.1/pkg/compiler/analysis.go:277
github.com/nspcc-dev/neo-go/pkg/compiler.(*codegen).compile(0xc0003f54a0, 0xc0007a6f30, 0x47ca98?)
        github.com/nspcc-dev/neo-go@v0.103.1/pkg/compiler/codegen.go:2211 +0xdc
github.com/nspcc-dev/neo-go/pkg/compiler.codeGen(0xc0007a6f30)
        github.com/nspcc-dev/neo-go@v0.103.1/pkg/compiler/codegen.go:2297 +0x38b
github.com/nspcc-dev/neo-go/pkg/compiler.CompileWithOptions({0x7ffe95a024b5?, 0x3?}, {0x0?, 0x0?}, 0xc0001d22d0)
        github.com/nspcc-dev/neo-go@v0.103.1/pkg/compiler/compiler.go:249 +0x67
github.com/nspcc-dev/neo-go/pkg/compiler.CompileAndSave({0x7ffe95a024b5, 0x8}, 0xc0001d22d0)
        github.com/nspcc-dev/neo-go@v0.103.1/pkg/compiler/compiler.go:265 +0x2a5
github.com/nspcc-dev/neo-go/cli/smartcontract.contractCompile(0xc0002ac9a0)
        github.com/nspcc-dev/neo-go@v0.103.1/cli/smartcontract/smart_contract.go:479 +0xc29
github.com/urfave/cli.HandleAction({0xff72a0?, 0x1333608?}, 0x7?)
        github.com/urfave/cli@v1.22.5/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x11ded98, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x120aadf, 0x27}, {0x1236cda, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.5/command.go:173 +0x63e
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000211dc0, 0xc0002ac580)
        github.com/urfave/cli@v1.22.5/app.go:405 +0xdc7
github.com/urfave/cli.Command.startApp({{0x11e0474, 0x8}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x120bee7, 0x28}, {0x0, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.5/command.go:372 +0xb58
github.com/urfave/cli.Command.Run({{0x11e0474, 0x8}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x120bee7, 0x28}, {0x0, ...}, ...}, ...)
        github.com/urfave/cli@v1.22.5/command.go:102 +0x7e5
github.com/urfave/cli.(*App).Run(0xc000211c00, {0xc00003e340, 0xd, 0xd})
        github.com/urfave/cli@v1.22.5/app.go:277 +0xb07
main.main()
        github.com/nspcc-dev/neo-go@v0.103.1/cli/main.go:12 +0x2d
make: *** [Makefile:43: alphabet/alphabet_contract.nef] Error 2
```

## Expected Behavior
`import cycle not allowed` or something like that, NO PANIC, KEEP CALM, WE ARE OK.

## Steps to Reproduce

Try `make archive` here: https://github.com/carpawell/neofs-contract/tree/dont-die-pls.

```
package github.com/nspcc-dev/neofs-contract/alphabet
        imports github.com/nspcc-dev/neofs-contract/common
        imports github.com/nspcc-dev/neofs-contract/netmap
        imports github.com/nspcc-dev/neofs-contract/common: import cycle not allowed
```

## Context

Tried to build contracts with cycled imports and failed.

## Regression

Not sure, first time met this.

## Your Environment

`v0.103.1`

**Comment by roman-khimov** [comment]
I'd expect Go parser to catch this (we're dealing with already parsed AST), but looks like it's a bit more complicated than that.

**Comment by roman-khimov** [comment]
It's interesting in that if you're to try compiling `netmap`, it'd be like
```
error while trying to compile smart contract file: -: import cycle not allowed: import stack: [github.com/nspcc-dev/neofs-contract/netmap github.com/nspcc-dev/neofs-contract/common github.com/nspcc-dev/neofs-contract/netmap]
```
But when you're trying to compile `alphabet` or other contracts it breaks this way.
