### ISSUE TITLE
CN panic: unexpected external call to newEpochNextValidators cache

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#3253]
## Current Behavior
```
panic: bug: unexpected external call to newEpochNextValidators cache
goroutine 297 [running]:
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).ComputeNextBlockValidators(0x20?, 0x2?)
        github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:1132 +0x68
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).ComputeNextBlockValidators(0xc001824478?)
        github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:2736 +0x25
github.com/nspcc-dev/neo-go/pkg/consensus.(*service).getValidators(0xc000859d40, {0xc0004b2800?, 0x11392c0?, 0xc0036a9620?})
        github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:688 +0x42
github.com/nspcc-dev/dbft.(*Context).Fill(0xc00028f8c0)
        github.com/nspcc-dev/dbft@v0.0.0-20230515113611-25db6ba61d5c/context.go:268 +0x222
github.com/nspcc-dev/dbft.(*Context).makePrepareRequest(0xc00028f8c0)
        github.com/nspcc-dev/dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:19 +0x1c
github.com/nspcc-dev/dbft.(*DBFT).sendPrepareRequest(0xc00028f8c0)
        github.com/nspcc-dev/dbft@v0.0.0-20230515113611-25db6ba61d5c/send.go:31 +0x29
github.com/nspcc-dev/dbft.(*DBFT).OnTimeout(0xc00028f8c0, {0x11e2a2b?, 0x0?})
        github.com/nspcc-dev/dbft@v0.0.0-20230515113611-25db6ba61d5c/dbft.go:190 +0x3d5
github.com/nspcc-dev/neo-go/pkg/consensus.(*service).eventLoop(0xc000859d40)
        github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:314 +0x368
created by github.com/nspcc-dev/neo-go/pkg/consensus.(*service).Start in goroutine 116
        github.com/nspcc-dev/neo-go/pkg/consensus/consensus.go:285 +0x125
```

## Expected Behavior
No panic.

## Possible Solution
Fix the damn thing!

## Steps to Reproduce
Run CN. Nothing else known, but likely some votes and committee changes are needed.

## Your Environment
* Version of the product used: 0.104.0, linux-amd64

**Comment by roman-khimov** [comment]
87 cases in 12 hours.
