### ISSUE TITLE
APPEND can return NULL?

### ISSUE THREAD

**Issue by Slava0135** [nspcc-dev/neo-go#3701]
Have been fuzzing VM again and found this.

## Problem
```
NEO-GO-VM > loadbase64 EMNKSs8=
READY: loaded 5 instructions
NEO-GO-VM 0 > ops
INDEX    OPCODE      PARAMETER
0        PUSH0           <<
1        NEWARRAY    
2        DUP         
3        DUP         
4        APPEND      

NEO-GO-VM 0 > run
[
    null
]
```

But i am not sure if this is intended because C# implementation throws exception when calling `ToJson`:

```
Unhandled exception. System.InvalidOperationException: Circular reference.
   at Neo.VM.Helper.ToJson(StackItem item, HashSet`1 context, Int32& maxSize)
   at Neo.VM.Helper.ToJson(StackItem item, HashSet`1 context, Int32& maxSize)
...
```

There is no such case in tests, so i am asking here.

**Comment by roman-khimov** [comment]
I think that you don't have a real `null` here in fact, likely that's just the way it's stubbed out (because it can't be JSONized/represented). This can be checked by some lower-level UT. But I'm surprised by the C# exception. Related to https://github.com/neo-project/neo/pull/3581, I think that after it happens the behavior will just be the same as in NeoGo.

**Comment by roman-khimov** [comment]
> throws exception when calling ToJson

Ah. Sorry, haven't noticed immediately. I think that the VM behavior is the same then and will remain the same. But then we have different JSONization choices at different places. RPC call would give a different output, for example. And C# exception is fine, it's also handled in various places dealing with JSON.
