### ISSUE TITLE
How to make a transaction from one account to another?

### ISSUE THREAD

**Issue by godlovericea** [nspcc-dev/neo-go#3733]
I have a  keyrig project, i want to transfer NEO/GAS  to another account, how to do it by go program ?

the golang program  below:
it panic with errors:
script failed (FAULT state) due to an error: Called Contract Does Not Exist: 0x32a5b5ca3ad394846d3d4030f4e5a4729ec37f97.transfer
--- FAIL: Test_Make_TX_nep17 (16.95s)

```
func Make_TX_nep17() {
	privateKey, _ := keys.NewPrivateKeyFromHex("9c6d63388319235fc270521a59c0b7c4b87ef3e905b0cdcc424ee1e63eecccc5")
	acc := wallet.NewAccountFromPrivateKey(privateKey)
	client, _ := rpcclient.New(context.Background(), "http://seed5t5.neo.org:20332", rpcclient.Options{})
	// Create a simple CalledByEntry-scoped actor (assuming there is an account inside the wallet).
	Actor, _ := actor.NewSimple(client, acc)
	// NEOTOKEN
	nep17Hash, _ := address.StringToUint160("0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5")

	token := nep17.New(Actor, nep17Hash)

	from, _ := address.StringToUint160("NZj2GvuMhNE8G18ADWFe1XE3hyxYSAeQY5")
	to, _ := address.StringToUint160("NdypBhqkz2CMMnwxBgvoC9X2XjKF5axgKo")

	amount := big.NewInt(10)

	tx, err := token.TokenWriter.TransferTransaction(from, to, amount, nil)
	if err != nil {
		fmt.Println(err)

		// err message:
		// script failed (FAULT state) due to an error: Called Contract Does Not Exist: 0x32a5b5ca3ad394846d3d4030f4e5a4729ec37f97.transfer
		// --- FAIL: Test_Make_TX_nep17 (16.95s)
	}
	// TokenWriter TransferTransaction
	txHash, txId, err := Actor.SignAndSend(tx)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("txHash:", txHash)
	fmt.Println("txId:", txId)

}
```

**Comment by roman-khimov** [comment]
1. Check errors, don't ignore them. They will tell you where the error is.
2. `nep17Hash, _ := address.StringToUint160("0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5")` can't work, it's not an address.
3. You can use NEO-specific actor, not a generic NEP-17 one, see https://pkg.go.dev/github.com/nspcc-dev/neo-go/pkg/rpcclient/neo
4. `SignAndSend()` returns hash, VUB and error, VUB is not a txID.
5. You can call `token.Transfer()` directly if you want to just create a transaction (and `Actor.Wait()` for it if you need a result.

**Comment by godlovericea** [comment]
I am so sorry, thanks to reply my question, I have not represent my problem.
I have a keyring project, I want to make ``` tx *transaction.Transaction ``` for transfer  NEO or  GAS
Then, another one send my ``` tx ```

```
func Make_TX_nep17() {
	privateKey, err := keys.NewPrivateKeyFromHex("9c6d63388319235fc270521a59c0b7c4b87ef3e905b0cdcc424ee1e63eecccc5")
	if err != nil {
		fmt.Println(err)
	}
	acc := wallet.NewAccountFromPrivateKey(privateKey)
	client, err := rpcclient.New(context.Background(), "http://seed5t5.neo.org:20332", rpcclient.Options{})
	if err != nil {
		fmt.Println(err)
	}
	// Create a simple CalledByEntry-scoped actor (assuming there is an account inside the wallet).
	Actor, err := actor.NewSimple(client, acc)
	if err != nil {
		fmt.Println(err)
	}
	// NEOTOKEN
	// I don know what's mean ?
	nep17Hash, err := address.StringToUint160("0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5")
	if err != nil {
		fmt.Println(err)
		return
		// error: invalid base58 digit ('0')
	}
	token := nep17.New(Actor, nep17Hash)

	from, err := address.StringToUint160("NZj2GvuMhNE8G18ADWFe1XE3hyxYSAeQY5")
	if err != nil {
		fmt.Println(err)
	}
	to, err := address.StringToUint160("NdypBhqkz2CMMnwxBgvoC9X2XjKF5axgKo")
	if err != nil {
		fmt.Println(err)
	}

	amount := big.NewInt(10)

	tx, err := token.TokenWriter.TransferTransaction(from, to, amount, nil)
	if err != nil {
		fmt.Println(err)

		// err message:
		// 		senderActor: {0xc000014240 [{[151 127 195 158 114 164 229 244 48 64 61 109 132 148 211 58 202 181 165 50] 1 [] [] []}]}
		// script failed (FAULT state) due to an error: Called Contract Does Not Exist: 0x32a5b5ca3ad394846d3d4030f4e5a4729ec37f97.transfer
		// --- FAIL: Test_Make_TX_nep17 (16.95s)
	}
	// TokenWriter TransferTransaction
	txHash, ValidUntilBlock, err := Actor.SignAndSend(tx)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("txHash:", txHash)
	fmt.Println("ValidUntilBlock:", ValidUntilBlock)
}
```

**Comment by godlovericea** [comment]
I have another version of tx, such as below:

```
func NEOAddress_N3() {
	acc, err := wallet.NewAccount()
	if err != nil {
		fmt.Println("生成账户出错：", err)
	}
	fmt.Println("address:", acc.Address)
	fmt.Println("PrivateKey:", acc.PrivateKey())
	fmt.Println("Contract hash:", acc.Contract.ScriptHash())
	fmt.Println("PublicKey:", acc.PublicKey())
	acc.ScriptHash()
}

func Make_TX_ExampleContract() {
	privateKey, err := keys.NewPrivateKeyFromHex("9c6d63388319235fc270521a59c0b7c4b87ef3e905b0cdcc424ee1e63eecccc5")
	if err != nil {
		fmt.Println(err)
	}
	acc := wallet.NewAccountFromPrivateKey(privateKey)
	fmt.Println(acc.Address)
	client, err := rpcclient.New(context.Background(), "http://seed5t5.neo.org:20332", rpcclient.Options{})
	if err != nil {
		fmt.Println(err)
	}
	a, err := actor.NewSimple(client, acc)
	if err != nil {
		fmt.Println(err)
	}
	neoToken := neo.New(a)
	from, err := address.StringToUint160("NZj2GvuMhNE8G18ADWFe1XE3hyxYSAeQY5")
	if err != nil {
		fmt.Println(err)
	}
	to, err := address.StringToUint160("NNSHbGcbDpx2jVCEwrcBarfZczqDhpspbS")
	if err != nil {
		fmt.Println(err)
	}
	txid, vub, err := neoToken.Transfer(from, to, big.NewInt(1), nil)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("txid:", txid)
	fmt.Println("vub:", vub)
}

func Make_NewTransferFromOwner() (*transaction.Transaction, error) {
	privateKey, err := keys.NewPrivateKeyFromHex("9c6d63388319235fc270521a59c0b7c4b87ef3e905b0cdcc424ee1e63eecccc5")
	if err != nil {
		fmt.Println(err)
	}
	acc := wallet.NewAccountFromPrivateKey(privateKey)
	fmt.Println(acc.Address)
	// 0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5
	// NEO TOKEN contractHash
	contractHash, err := address.StringToUint160("NiHURyS83nX2mpxtA7xq84cGxVbHojj5Wc")
	if err != nil {
		fmt.Println(err)
	}
	ownerHash := acc.ScriptHash()
	to, err := address.StringToUint160("NNSHbGcbDpx2jVCEwrcBarfZczqDhpspbS")
	if err != nil {
		fmt.Println(err)
	}
	amount := big.NewInt(1)
	script, err := smartcontract.CreateCallWithAssertScript(contractHash, "transfer", ownerHash, to, amount, nil)
	if err != nil {
		return nil, err
	}

	tx := transaction.New(script, 11000000)
	tx.ValidUntilBlock = 6480024

	tx.Nonce = 1
	tx.Signers = []transaction.Signer{{
		Account:          ownerHash,
		Scopes:           transaction.CalledByEntry,
		AllowedContracts: nil,
		AllowedGroups:    nil,
	}}
	client, err := rpcclient.New(context.Background(), "http://seed5t5.neo.org:20332", rpcclient.Options{})
	if err != nil {
		fmt.Println(err)
	}
	hash, err := client.SendRawTransaction(tx)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(hash)
	return tx, nil
}
```

but it throw error:

```
Invalid params - Invalid Transaction Format: "AAEAAADA2KcAAAAAAAAAAAAAAAAAmOBiAAGXf8OecqTl9DBAPW2ElNM6yrWlMgEAVwsRDBQbrBgwW\u002BY4evCRff9ZEDUCGvmEBwwUl3/DnnKk5fQwQD1thJTTOsq1pTIUwB8MCHRyYW5zZmVyDBT1Y\u002BpAvCg9TQ4FxI6jBbPyoHNA70FifVtSOQA=" -    at Neo.Plugins.Result.Ok_Or[T](Func`1 function, RpcError err, Boolean withData)
   at Neo.Plugins.RpcServer.SendRawTransaction(JArray _params)
   at Neo.Plugins.RpcServer.ProcessRequestAsync(HttpContext context, JObject request) (-32602) -    at Neo.Plugins.Result.Ok_Or[T](Func`1 function, RpcError err, Boolean withData)
   at Neo.Plugins.RpcServer.SendRawTransaction(JArray _params)
   at Neo.Plugins.RpcServer.ProcessRequestAsync(HttpContext context, JObject request)
```

I do not know how to deal with it

**Comment by AnnaShaleva** [comment]
Your transaction is unsigned. You need to sign it with your ptivate key before the sending. You may refer to https://github.com/nspcc-dev/neo-go-sc-wrkshp/blob/c0d3328aa423d84767eee4089fe47f47410c8fe0/dApp/dApp.go#L327 and to https://github.com/nspcc-dev/neo-go-sc-wrkshp/blob/c0d3328aa423d84767eee4089fe47f47410c8fe0/dApp/dApp.go#L398 for an example of GAS transfer. NEO transfer can be constructed the same way.

**Comment by godlovericea** [comment]
@AnnaShaleva  Thank you very much!  I still want to know how to make tx  on NEO N3 network  with  ```FLM```  coin

**Comment by AnnaShaleva** [comment]
`FLM` is a NEP-17 token. Use `Actor` to construct transfer transactions, the links posted in https://github.com/nspcc-dev/neo-go/issues/3733#issuecomment-2530764096 are for this question. In particular, see https://github.com/nspcc-dev/neo-go-sc-wrkshp/blob/c0d3328aa423d84767eee4089fe47f47410c8fe0/dApp/dApp.go#L368 for an example of `nep17` package usage.
