### ISSUE TITLE
Panic on RPC request serving due to concurrent new peer connection

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3752]
## Current Behavior
```
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: INFO        new peer connected        {"addr": "3.112.138.57:61112", "peerCount": 31}
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: 2024/12/13 09:56:08 http: panic serving 127.0.0.1:43214: runtime error: invalid memory address or nil pointer dereference
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: goroutine 25293644 [running]:
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: net/http.(*conn).serve.func1()
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         net/http/server.go:1947 +0xbe
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: panic({0x1193140?, 0x1f51a00?})
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         runtime/panic.go:785 +0x132
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: github.com/nspcc-dev/neo-go/pkg/network.(*Server).ConnectedPeers(0xc000f44a08)
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         github.com/nspcc-dev/neo-go/pkg/network/server.go:459 +0x254
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).getPeers(0xc000ea2a08, {0xc000312330?, 0xc000a833d0?, 0x8?})
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:904 +0x8d
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleIn(0xc000ea2a08, 0xc002a7ddb0, 0x0)
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:645 +0x60a
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleRequest(0xc000ea2a08, 0xc00b47c140, 0x0)
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:571 +0xd1
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleHTTPRequest(0xc000ea2a08, {0x15efb60, 0xc001f20620}, 0xc001f38a00)
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:551 +0x9ea
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: net/http.HandlerFunc.ServeHTTP(0x410845?, {0x15efb60?, 0xc001f20620?}, 0xc001f20601?)
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         net/http/server.go:2220 +0x29
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: net/http.serverHandler.ServeHTTP({0x15e9970?}, {0x15efb60?, 0xc001f20620?}, 0x6?)
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         net/http/server.go:3210 +0x8e
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: net/http.(*conn).serve(0xc0034c0750, {0x15f1980, 0xc0009bbe90})
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         net/http/server.go:2092 +0x5d0
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]: created by net/http.(*Server).Serve in goroutine 782
Dec 13 09:56:08 kaede neogo-mainnet-rpc[1894253]:         net/http/server.go:3360 +0x485
Dec 13 09:56:12 kaede neogo-mainnet-rpc[1894253]: INFO        new peer connected        {"addr": "3.112.138.57:20513", "peerCount": 32}
Dec 13 09:56:13 kaede neogo-mainnet-rpc[1894253]: INFO        peer disconnected        {"addr": "3.112.138.57:20513", "error": "read tcp 157.90.177.38:10333->3.112.138.57:20513: read: connection reset by peer", "peerCount": 31}
```

## Expected Behavior
No panic.

**Comment by roman-khimov** [comment]
```
net/http.serverHandler.ServeHTTP({0x15cfdd0?}, {0x15d5bc0?, 0xc00af040e0?}, 0x6?)
github.com/nspcc-dev/neo-go/pkg/network.(*Server).ConnectedPeers(0xc002c6cf08)
	runtime/panic.go:785 +0x132
	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:556 +0x9ea
github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleRequest(0xc002776788, 0xc0016d55a0, 0x0)
	net/http/server.go:3210 +0x8e
github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).getPeers(0xc002776788, {0xc000120300?, 0xc0071274d0?, 0x8?})
	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:650 +0x60a
	net/http/server.go:3360 +0x485
net/http.HandlerFunc.ServeHTTP(0x410705?, {0x15d5bc0?, 0xc00af040e0?}, 0xc00af04001?)
github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleHTTPRequest(0xc002776788, {0x15d5bc0, 0xc00af040e0}, 0xc009bf57c0)
	github.com/nspcc-dev/neo-go/pkg/network/server.go:524 +0x254
	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:576 +0xd1
	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:909 +0x8d
panic({0x117de40?, 0x1f09df0?})
net/http.(*conn).serve(0xc009bcc750, {0x15d7ac0, 0xc000463e90})
github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleIn(0xc002776788, 0xc010e66fa0, 0x0)
net/http.(*conn).serve.func1()
2025/03/04 15:36:21 http: panic serving 127.0.0.1:58604: runtime error: invalid memory address or nil pointer dereference
	net/http/server.go:2092 +0x5d0
goroutine 38753140 [running]:
	net/http/server.go:2220 +0x29
created by net/http.(*Server).Serve in goroutine 237
	net/http/server.go:1947 +0xbe
```
Happens frequently.

**Comment by AnnaShaleva** [comment]
A little bit different entry, but the source of the problem is the same:
```
1742884281640	panic({0x117de40?, 0x1f09df0?})
1742884281640		net/http/server.go:2220 +0x29
1742884281640	net/http.(*conn).serve(0xc00398a7e0, {0x15d7ac0, 0xc000ac74a0})
1742884281640	2025/03/25 06:31:21 http: panic serving 127.0.0.1:49490: runtime error: invalid memory address or nil pointer dereference
1742884281640		github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:650 +0x60a
1742884281640		github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:556 +0x9ea
1742884281640	created by net/http.(*Server).Serve in goroutine 1132
1742884281640		net/http/server.go:3360 +0x485
1742884281640	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).getPeers(0xc000d06f08, {0xc000335d10?, 0xc0022bd070?, 0x8?})
1742884281640		net/http/server.go:2092 +0x5d0
1742884281640	net/http.serverHandler.ServeHTTP({0x15cfdd0?}, {0x15d5bc0?, 0xc0001a5c00?}, 0x6?)
1742884281640	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleRequest(0xc000d06f08, 0xc000a7a820, 0x0)
1742884281640	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleHTTPRequest(0xc000d06f08, {0x15d5bc0, 0xc0001a5c00}, 0xc00210d040)
1742884281640		runtime/panic.go:785 +0x132
1742884281640	goroutine 29330866 [running]:
1742884281640		net/http/server.go:3210 +0x8e
1742884281640		github.com/nspcc-dev/neo-go/pkg/network/server.go:524 +0x254
1742884281640		github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:576 +0xd1
1742884281640	github.com/nspcc-dev/neo-go/pkg/network.(*Server).ConnectedPeers(0xc000842f08)
1742884281640		github.com/nspcc-dev/neo-go/pkg/services/rpcsrv/server.go:909 +0x8d
1742884281640	net/http.(*conn).serve.func1()
1742884281640	net/http.HandlerFunc.ServeHTTP(0x410705?, {0x15d5bc0?, 0xc0001a5c00?}, 0xc0001a5c01?)
1742884281640		net/http/server.go:1947 +0xbe
1742884281640	github.com/nspcc-dev/neo-go/pkg/services/rpcsrv.(*Server).handleIn(0xc000d06f08, 0xc00567fea0, 0x0)
```
