### ISSUE TITLE
Panic inside `io.PutVarUint`

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neo-go#3766]
## Current Behavior
```
panic: runtime error: index out of range [8] with length 5 [recovered]
	panic: runtime error: index out of range [8] with length 5

goroutine 19 [running]:
testing.tRunner.func1.2({0x5dd0c0, 0xc0000f6180})
	/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0x5dd0c0?, 0xc0000f6180?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/nspcc-dev/neo-go/pkg/io.PutVarUint(...)
	/home/ll/projects/neo/go/pkg/io/binaryWriter.go:109
github.com/nspcc-dev/neo-go/pkg/io_test.TestPutVarUint(0xc0000d8b60?)
```

## Expected Behavior
no panic when buffer has enough len, only otherwise (similar to https://pkg.go.dev/encoding/binary#PutUvarint)

## Possible Solution
do not do https://github.com/nspcc-dev/neo-go/blob/9189b3eb7dcab1a86d8acc66269e3826c4c75515/pkg/io/binaryWriter.go#L109

## Steps to Reproduce
```go
func TestPutVarUint(t *testing.T) {
	const n = uint64(123456787890)
	io.PutVarUint(make([]byte, io.GetVarSize(n)), n)
}
```

## Regression
no

## Your Environment
* Version of the product used: v0.107.2

**Comment by roman-khimov** [comment]
This one was added specifically as canary (17a3f17c74). At the same time users of this API can expect some symmetry between `GetVarSize()` and `PutVarUint()`. And it'll fail later if buffer is too short.

**Comment by cthulhu-rider** [comment]
`io.GetVarSize(uint64(math.MaxInt + 1))` returns `1` which is also unexpected to me. Caused by cast https://github.com/nspcc-dev/neo-go/blob/9189b3eb7dcab1a86d8acc66269e3826c4c75515/pkg/io/size.go#L58

**Comment by cthulhu-rider** [comment]
> At the same time users of this API can expect some symmetry between GetVarSize() and PutVarUint().

exactly. But this is unexpected even within oneself:
```go
func TestPutVarUint(t *testing.T) {
	const n = uint64(123)
	b := make([]byte, 32)
	ln := io.PutVarUint(b, n)
	io.PutVarUint(b[:ln], n)
}
```
```
panic: runtime error: index out of range [8] with length 1 [recovered]
	panic: runtime error: index out of range [8] with length 1
```
