### ISSUE TITLE
Create integration tests emulating weak network

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#526]
Justification:
During  teal time work we have an issue with one node which dies because of OoM.
Probable root cause is network misconfiguration.

Solution:
Create a test to simulate weak and non stable network. Fix the issue. Add this test to smoke test suite.

**Comment by fyrchik** [comment]
It will also be useful to see how a peer with reliable but very slow connection can affect the rest of the network.

**Comment by volekerb** [comment]
We still have a node with bad performance because of issues on HDD. 
I think we can emulate this by having 
1. Separate docker with DB
2. One docker with node connected to the 1st one
3. Pumba configured for bad network between those two. (https://github.com/alexei-led/pumba)

**Comment by volekerb** [comment]
Or probably try to run with docker flag `--device-read-bp`

**Comment by volekerb** [comment]
also found https://www.scylladb.com/2016/02/16/fault-injection-filesystem-software-testing/

**Comment by volekerb** [comment]
HDD speed on PC with neo-go:
```
$ dd if=/dev/zero of=/tmp/output conv=fdatasync bs=384k count=1k; rm -f /tmp/output
1024+0 records in
1024+0 records out
402653184 bytes (403 MB, 384 MiB) copied, 8.42048 s, 47.8 MB/s
```
local pc:
```
dd if=/dev/zero of=/tmp/output bs=384k count=1k; rm -f /tmp/output
1024+0 records in
1024+0 records out
402653184 bytes transferred in 0.651364 secs (618169149 bytes/sec)
```
618169149 == 590 MB/s

To simulate:
` docker run -it --device-write-bps /dev/sda:50mb neo-go-experiment`

After simulating with 50MB/sec write limit and using LevelDB 20MB Ram leaked:
```
INFO[2033] blockchain persist completed                  blockHeight=58132 headerHeight=450000 persistedBlocks=5 persistedKeys=16 took="173.1µs"
```

**Comment by volekerb** [comment]
With BoltDB. It writes faster but required more memory =)
in 5 minutes ate 72MB

**Comment by volekerb** [comment]
Nice! With BoltDB app crashed:
```
INFO[1456] blockchain persist completed                  blockHeight=63480 headerHeight=1810000 persistedBlocks=1 persistedKeys=4 took=740.7113ms
fatal error: concurrent map read and map write

goroutine 322 [running]:
runtime.throw(0xc8a6dc, 0x21)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc003473958 sp=0xc003473928 pc=0x42e282
runtime.mapaccess2(0xb706a0, 0xc0001893b0, 0xc0034739c8, 0xc0028704e0, 0x3)
        /usr/local/go/src/runtime/map.go:470 +0x278 fp=0xc0034739a0 sp=0xc003473958 pc=0x40dc08
github.com/CityOfZion/neo-go/pkg/core.MemPool.ContainsKey(0xc0001d0d20, 0xc0001893b0, 0xc0001893e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /neo-go/pkg/core/mem_pool.go:92 +0xcb fp=0xc003473a30 sp=0xc0034739a0 pc=0x9326db
github.com/CityOfZion/neo-go/pkg/core.(*Blockchain).HasTransaction(0xc0001ca8c0, 0x49f0b45d430e441b, 0x553db79b7072821c, 0x28969518de11976, 0xba5100efddbe79d4, 0xc003473cd0)
        /neo-go/pkg/core/blockchain.go:803 +0xa1 fp=0xc003473b68 sp=0xc003473a30 pc=0x914b11
github.com/CityOfZion/neo-go/pkg/core.Blockchainer.HasTransaction-fm(0x49f0b45d430e441b, 0x553db79b7072821c, 0x28969518de11976, 0xba5100efddbe79d4, 0xc005a5d388)
        /neo-go/pkg/core/blockchainer.go:28 +0x46 fp=0xc003473ba8 sp=0xc003473b68 pc=0x997326
github.com/CityOfZion/neo-go/pkg/network.(*Server).handleInvCmd(0xc00018f680, 0xd9d980, 0xc00025e190, 0xc005a5d380, 0x0, 0x0)
        /neo-go/pkg/network/server.go:401 +0x3bb fp=0xc003473d38 sp=0xc003473ba8 pc=0x9924cb
github.com/CityOfZion/neo-go/pkg/network.(*Server).handleMessage(0xc00018f680, 0xd9d980, 0xc00025e190, 0xc007a0d050, 0x0, 0x0)
        /neo-go/pkg/network/server.go:582 +0x1ae fp=0xc003473da0 sp=0xc003473d38 pc=0x993bbe
github.com/CityOfZion/neo-go/pkg/network.(*TCPTransport).handleConn(0xc000228420, 0xd9b880, 0xc0001b6f00)
        /neo-go/pkg/network/tcp_transport.go:93 +0x202 fp=0xc003473fc8 sp=0xc003473da0 pc=0x996672
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc003473fd0 sp=0xc003473fc8 pc=0x45b3e1
created by github.com/CityOfZion/neo-go/pkg/network.(*TCPTransport).Dial
        /neo-go/pkg/network/tcp_transport.go:36 +0xb4

goroutine 1 [select, 23 minutes]:
github.com/CityOfZion/neo-go/cli/server.startServer(0xc0001942c0, 0x0, 0x0)
        /neo-go/cli/server/server.go:300 +0x8c7
github.com/urfave/cli.HandleAction(0xb579e0, 0xca67a8, 0xc0001942c0, 0xc000184300, 0x0)
        /neo-go/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0xc75a65, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc7bfe7, 0x10, 0x0, ...)
        /neo-go/vendor/github.com/urfave/cli/command.go:210 +0x991
github.com/urfave/cli.(*App).Run(0xc00018a820, 0xc0000a8000, 0x5, 0x5, 0x0, 0x0)
        /neo-go/vendor/github.com/urfave/cli/app.go:255 +0x6ab
main.main()
        /neo-go/cli/main.go:25 +0x841

goroutine 18 [syscall, 23 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 54 [chan receive, 23 minutes]:
github.com/CityOfZion/neo-go/cli/server.newGraceContext.func1(0xc000184480, 0xc00018caf0)
        /neo-go/cli/server/server.go:87 +0x34
created by github.com/CityOfZion/neo-go/cli/server.newGraceContext
        /neo-go/cli/server/server.go:86 +0xef

goroutine 56 [chan receive, 23 minutes]:
github.com/CityOfZion/neo-go/pkg/network.(*DefaultDiscovery).run(0xc000185620)
        /neo-go/pkg/network/discovery.go:179 +0x288
created by github.com/CityOfZion/neo-go/pkg/network.NewDefaultDiscovery
        /neo-go/pkg/network/discovery.go:52 +0x13c

goroutine 59 [select]:
github.com/CityOfZion/neo-go/pkg/core.(*Blockchain).Run(0xc0001ca8c0)
        /neo-go/pkg/core/blockchain.go:202 +0x15c
created by github.com/CityOfZion/neo-go/cli/server.startServer
        /neo-go/cli/server/server.go:288 +0x574

goroutine 60 [select, 20 minutes]:
github.com/CityOfZion/neo-go/pkg/network.(*Server).run(0xc00018f680)
        /neo-go/pkg/network/server.go:197 +0x17c
github.com/CityOfZion/neo-go/pkg/network.(*Server).Start(0xc00018f680, 0xc000217980)
        /neo-go/pkg/network/server.go:160 +0x2e1
created by github.com/CityOfZion/neo-go/cli/server.startServer
        /neo-go/cli/server/server.go:289 +0x5a6

goroutine 61 [IO wait, 23 minutes]:
internal/poll.runtime_pollWait(0x7fd2306eef08, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001c6698, 0x72, 0x0, 0x0, 0xc76b82)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0001c6680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc0001c6680, 0xc000267bf0, 0xc000050a80, 0x7fd232a20460)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0002265c0, 0xc000267c20, 0x40c618, 0x30)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0002265c0, 0xbfb400, 0xc000228ba0, 0xb7adc0, 0x12ca450)
        /usr/local/go/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc0001d4700, 0xd91280, 0xc0002265c0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2896 +0x286
net/http.(*Server).ListenAndServe(0xc0001d4700, 0xc000000004, 0xc000097e50)
        /usr/local/go/src/net/http/server.go:2825 +0xb7
github.com/CityOfZion/neo-go/pkg/rpc.(*Server).Start(0xc0001bcf00, 0xc000217980)
        /neo-go/pkg/rpc/server.go:62 +0x1e6
created by github.com/CityOfZion/neo-go/cli/server.startServer
        /neo-go/cli/server/server.go:290 +0x5d8

goroutine 62 [IO wait, 23 minutes]:
internal/poll.runtime_pollWait(0x7fd2306eefd8, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001c6618, 0x72, 0x0, 0x0, 0xc76b82)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0001c6600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc0001c6600, 0xc000096bf8, 0xc000050a80, 0x7fd232a20460)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000226580, 0xc000096c28, 0x40c618, 0x30)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000226580, 0xbfb400, 0xc0002289f0, 0xb7adc0, 0x12ca450)
        /usr/local/go/src/net/tcpsock.go:261 +0x47
net/http.(*Server).Serve(0xc0001d47e0, 0xd91280, 0xc000226580, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2896 +0x286
net/http.(*Server).ListenAndServe(0xc0001d47e0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2825 +0xb7
github.com/CityOfZion/neo-go/pkg/network/metrics.(*Service).Start(0xc000228870)
        /neo-go/pkg/network/metrics/metrics.go:38 +0x50
created by github.com/CityOfZion/neo-go/cli/server.startServer
        /neo-go/cli/server/server.go:291 +0x5fd

goroutine 40 [runnable]:
github.com/CityOfZion/neo-go/pkg/vm.(*VM).RegisterInteropFuncs(0xc0003719e0, 0xc0038c1a70)
        /neo-go/pkg/vm/vm.go:127 +0x85
github.com/CityOfZion/neo-go/pkg/core.(*Blockchain).spawnVMWithInterops(0xc0001ca8c0, 0xc0000a83c0, 0x14)
        /neo-go/pkg/core/blockchain.go:1414 +0xac
github.com/CityOfZion/neo-go/pkg/core.(*Blockchain).verifyHashAgainstScript(0xc0001ca8c0, 0x8b0f382b92d81f3, 0xecfe8e9878a2219a, 0x257b026a, 0xc005a1e3f0, 0xb684d8285d67c07b, 0x7806950714b68cc3, 0x6cd4dd1d255e6b73, 0x579e5594e9612772, 0xc0000a83c0, ...)
        /neo-go/pkg/core/blockchain.go:1443 +0x13e
github.com/CityOfZion/neo-go/pkg/core.(*Blockchain).verifyBlockWitnesses(0xc0001ca8c0, 0xc003ebb960, 0xc008561680, 0x41e26ea4f1196ca3, 0x19af194122dbbbe0)
        /neo-go/pkg/core/blockchain.go:1506 +0x350
github.com/CityOfZion/neo-go/pkg/core.(*Blockchain).VerifyBlock(0xc0001ca8c0, 0xc003ebb960, 0x0, 0x403173)
        /neo-go/pkg/core/blockchain.go:1007 +0x158
github.com/CityOfZion/neo-go/pkg/core.(*Blockchain).AddBlock(0xc0001ca8c0, 0xc003ebb960, 0xc006b33ee0, 0x1)
        /neo-go/pkg/core/blockchain.go:237 +0x69e
github.com/CityOfZion/neo-go/pkg/network.(*blockQueue).run(0xc0002261a0)
        /neo-go/pkg/network/blockqueue.go:39 +0x14c
created by github.com/CityOfZion/neo-go/pkg/network.(*Server).Start
        /neo-go/pkg/network/server.go:157 +0x260

goroutine 41 [IO wait, 23 minutes]:
internal/poll.runtime_pollWait(0x7fd2306eee38, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001c6718, 0x72, 0x0, 0x0, 0xc76b82)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0001c6700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc0001c6700, 0xc000099f28, 0xd93980, 0xc0000a2020)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000226600, 0xc000226600, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000226600, 0x3, 0xc000220130, 0x6, 0xd91280)
        /usr/local/go/src/net/tcpsock.go:261 +0x47
github.com/CityOfZion/neo-go/pkg/network.(*TCPTransport).Accept(0xc000228420)
        /neo-go/pkg/network/tcp_transport.go:51 +0x121
created by github.com/CityOfZion/neo-go/pkg/network.(*Server).Start
        /neo-go/pkg/network/server.go:158 +0x292

goroutine 129 [select]:
github.com/CityOfZion/neo-go/pkg/network.(*Server).startProtocol(0xc00018f680, 0xd9d980, 0xc0000303c0)
        /neo-go/pkg/network/server.go:308 +0x578
created by github.com/CityOfZion/neo-go/pkg/network.(*Server).handleMessage
        /neo-go/pkg/network/server.go:605 +0x95c

goroutine 109 [select]:
github.com/CityOfZion/neo-go/pkg/network.(*Server).startProtocol(0xc00018f680, 0xd9d980, 0xc00025e780)
        /neo-go/pkg/network/server.go:308 +0x578
created by github.com/CityOfZion/neo-go/pkg/network.(*Server).handleMessage
        /neo-go/pkg/network/server.go:605 +0x95c

goroutine 15 [select]:
github.com/CityOfZion/neo-go/pkg/network.(*Server).startProtocol(0xc00018f680, 0xd9d980, 0xc0000a8aa0)
        /neo-go/pkg/network/server.go:308 +0x578
created by github.com/CityOfZion/neo-go/pkg/network.(*Server).handleMessage
        /neo-go/pkg/network/server.go:605 +0x95c

goroutine 147 [select]:
github.com/CityOfZion/neo-go/pkg/network.(*Server).startProtocol(0xc00018f680, 0xd9d980, 0xc0000a8b40)
        /neo-go/pkg/network/server.go:308 +0x578
created by github.com/CityOfZion/neo-go/pkg/network.(*Server).handleMessage
        /neo-go/pkg/network/server.go:605 +0x95c

goroutine 108 [select]:
github.com/CityOfZion/neo-go/pkg/network.(*Server).startProtocol(0xc00018f680, 0xd9d980, 0xc0000302d0)
        /neo-go/pkg/network/server.go:308 +0x578
created by github.com/CityOfZion/neo-go/pkg/network.(*Server).handleMessage
        /neo-go/pkg/network/server.go:605 +0x95c

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x7fd2306ee2d8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001c7398, 0x72, 0x0, 0x4, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001c7380, 0xc0054871c0, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0001c7380, 0xc0054871c0, 0x4, 0x4, 0x0, 0x4, 0xc0054871c0)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e030, 0xc0054871c0, 0x4, 0x4, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x68
io.ReadAtLeast(0xd82da0, 0xc00000e030, 0xc0054871c0, 0x4, 0x4, 0x4, 0xc00413bc20, 0x0, 0x1)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
encoding/binary.Read(0xd82da0, 0xc00000e030, 0xd99f60, 0x12f8260, 0xb76e60, 0xc0048d2960, 0x1, 0xc0048d2960)
        /usr/local/go/src/encoding/binary/binary.go:239 +0x2d9
github.com/CityOfZion/neo-go/pkg/io.(*BinReader).ReadLE(...)
        /neo-go/pkg/io/binaryReader.go:39
github.com/CityOfZion/neo-go/pkg/network.(*Message).Decode(0xc0048d2960, 0xc000349e38, 0xc0000302d0, 0xc00953b440)
        /neo-go/pkg/network/message.go:152 +0x26c
github.com/CityOfZion/neo-go/pkg/network.(*TCPTransport).handleConn(0xc000228420, 0xd9b880, 0xc00000e030)
        /neo-go/pkg/network/tcp_transport.go:90 +0x1bf
created by github.com/CityOfZion/neo-go/pkg/network.(*TCPTransport).Dial
        /neo-go/pkg/network/tcp_transport.go:36 +0xb4

goroutine 114 [IO wait]:
internal/poll.runtime_pollWait(0x7fd2306eebc8, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0002aee18, 0x72, 0x13e600, 0x13e6b3, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0002aee00, 0xc008187a90, 0x13e6b3, 0x13e6b3, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0002aee00, 0xc008187a90, 0x13e6b3, 0x13e6b3, 0x5a8, 0x0, 0x0)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0001b6368, 0xc008187a90, 0x13e6b3, 0x13e6b3, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x68
io.ReadAtLeast(0xd82da0, 0xc0001b6368, 0xc00817c000, 0x14a143, 0x14a143, 0x14a143, 0x0, 0x0, 0x203002)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
encoding/binary.Read(0xd82da0, 0xc0001b6368, 0xd99f60, 0x12f8260, 0xb39500, 0xc00a2265a0, 0x30, 0xb48380)
        /usr/local/go/src/encoding/binary/binary.go:165 +0x4df
github.com/CityOfZion/neo-go/pkg/io.(*BinReader).ReadLE(...)
        /neo-go/pkg/io/binaryReader.go:39
github.com/CityOfZion/neo-go/pkg/network.(*Message).decodePayload(0xc008d387b0, 0xc0002c5e38, 0xd99f60, 0x12f8260)
        /neo-go/pkg/network/message.go:168 +0x77f
github.com/CityOfZion/neo-go/pkg/network.(*Message).Decode(0xc008d387b0, 0xc0002c5e38, 0xc00025e780, 0xc004435c80)
        /neo-go/pkg/network/message.go:163 +0x88
github.com/CityOfZion/neo-go/pkg/network.(*TCPTransport).handleConn(0xc000228420, 0xd9b880, 0xc0001b6368)
        /neo-go/pkg/network/tcp_transport.go:90 +0x1bf
created by github.com/CityOfZion/neo-go/pkg/network.(*TCPTransport).Dial
        /neo-go/pkg/network/tcp_transport.go:36 +0xb4

goroutine 13 [IO wait]:
```

**Comment by roman-khimov** [comment]
That's a separate issue not really related to BoltDB. It's induced by #533, although it's not the source of the problem.

**Comment by fyrchik** [comment]
I think this can be done in nspcc-dev/neo-bench, but I am not aware if docker allows to configure anything besides packet delay.
