### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by im-kulikov** [nspcc-dev/neo-go#612]
commit 9befd8d

```
2020-01-22T07:51:03.562Z        INFO    starting rpc-server     {"endpoint": ":20331"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x9ca6c7]

goroutine 81 [running]:
github.com/CityOfZion/neo-go/pkg/network.(*Server).Start(0x0, 0xc0001703c0)
        github.com/CityOfZion/neo-go@/pkg/network/server.go:163 +0x37
created by github.com/CityOfZion/neo-go/cli/server.startServer
        github.com/CityOfZion/neo-go@/cli/server/server.go:328 +0x43e
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa02535]

goroutine 1 [running]:
github.com/CityOfZion/neo-go/cli/server.startServer(0xc0001d2160, 0x0, 0x0)
        github.com/CityOfZion/neo-go@/cli/server/server.go:332 +0x515
github.com/urfave/cli.HandleAction(0xb75e40, 0xccf240, 0xc0001d2160, 0xc000124600, 0x0)
        github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0xc98888, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xca2995, 0x10, 0x0, ...)
        github.com/urfave/cli@v1.20.0/command.go:210 +0x991
github.com/urfave/cli.(*App).Run(0xc00017f040, 0xc000030050, 0x5, 0x5, 0x0, 0x0)
        github.com/urfave/cli@v1.20.0/app.go:255 +0x6ab
main.main()
        github.com/CityOfZion/neo-go@/cli/main.go:25 +0x8d8
```

**Comment by roman-khimov** [comment]
I guess I understand now what has happened, it's directly related to #588, you need to update configurations of consensus nodes and copy wallets into containers (see #603).
